// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_repository_test.go -package=usecase -source=usecase.go Repository
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/georgg2003/skeeper/internal/skeeper/pkg/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetUpdatedAfter mocks base method.
func (m *MockRepository) GetUpdatedAfter(ctx context.Context, userID int64, lastSync time.Time) ([]models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatedAfter", ctx, userID, lastSync)
	ret0, _ := ret[0].([]models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdatedAfter indicates an expected call of GetUpdatedAfter.
func (mr *MockRepositoryMockRecorder) GetUpdatedAfter(ctx, userID, lastSync any) *MockRepositoryGetUpdatedAfterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatedAfter", reflect.TypeOf((*MockRepository)(nil).GetUpdatedAfter), ctx, userID, lastSync)
	return &MockRepositoryGetUpdatedAfterCall{Call: call}
}

// MockRepositoryGetUpdatedAfterCall wrap *gomock.Call
type MockRepositoryGetUpdatedAfterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetUpdatedAfterCall) Return(arg0 []models.Entry, arg1 error) *MockRepositoryGetUpdatedAfterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetUpdatedAfterCall) Do(f func(context.Context, int64, time.Time) ([]models.Entry, error)) *MockRepositoryGetUpdatedAfterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetUpdatedAfterCall) DoAndReturn(f func(context.Context, int64, time.Time) ([]models.Entry, error)) *MockRepositoryGetUpdatedAfterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetVaultCrypto mocks base method.
func (m *MockRepository) GetVaultCrypto(ctx context.Context, userID int64) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVaultCrypto", ctx, userID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVaultCrypto indicates an expected call of GetVaultCrypto.
func (mr *MockRepositoryMockRecorder) GetVaultCrypto(ctx, userID any) *MockRepositoryGetVaultCryptoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVaultCrypto", reflect.TypeOf((*MockRepository)(nil).GetVaultCrypto), ctx, userID)
	return &MockRepositoryGetVaultCryptoCall{Call: call}
}

// MockRepositoryGetVaultCryptoCall wrap *gomock.Call
type MockRepositoryGetVaultCryptoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetVaultCryptoCall) Return(kdfSalt, masterVerifier []byte, err error) *MockRepositoryGetVaultCryptoCall {
	c.Call = c.Call.Return(kdfSalt, masterVerifier, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetVaultCryptoCall) Do(f func(context.Context, int64) ([]byte, []byte, error)) *MockRepositoryGetVaultCryptoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetVaultCryptoCall) DoAndReturn(f func(context.Context, int64) ([]byte, []byte, error)) *MockRepositoryGetVaultCryptoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutVaultCrypto mocks base method.
func (m *MockRepository) PutVaultCrypto(ctx context.Context, userID int64, kdfSalt, masterVerifier []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutVaultCrypto", ctx, userID, kdfSalt, masterVerifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutVaultCrypto indicates an expected call of PutVaultCrypto.
func (mr *MockRepositoryMockRecorder) PutVaultCrypto(ctx, userID, kdfSalt, masterVerifier any) *MockRepositoryPutVaultCryptoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutVaultCrypto", reflect.TypeOf((*MockRepository)(nil).PutVaultCrypto), ctx, userID, kdfSalt, masterVerifier)
	return &MockRepositoryPutVaultCryptoCall{Call: call}
}

// MockRepositoryPutVaultCryptoCall wrap *gomock.Call
type MockRepositoryPutVaultCryptoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryPutVaultCryptoCall) Return(arg0 error) *MockRepositoryPutVaultCryptoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryPutVaultCryptoCall) Do(f func(context.Context, int64, []byte, []byte) error) *MockRepositoryPutVaultCryptoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryPutVaultCryptoCall) DoAndReturn(f func(context.Context, int64, []byte, []byte) error) *MockRepositoryPutVaultCryptoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpsertEntries mocks base method.
func (m *MockRepository) UpsertEntries(ctx context.Context, userID int64, entries []models.Entry) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEntries", ctx, userID, entries)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertEntries indicates an expected call of UpsertEntries.
func (mr *MockRepositoryMockRecorder) UpsertEntries(ctx, userID, entries any) *MockRepositoryUpsertEntriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEntries", reflect.TypeOf((*MockRepository)(nil).UpsertEntries), ctx, userID, entries)
	return &MockRepositoryUpsertEntriesCall{Call: call}
}

// MockRepositoryUpsertEntriesCall wrap *gomock.Call
type MockRepositoryUpsertEntriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpsertEntriesCall) Return(arg0 []uuid.UUID, arg1 error) *MockRepositoryUpsertEntriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpsertEntriesCall) Do(f func(context.Context, int64, []models.Entry) ([]uuid.UUID, error)) *MockRepositoryUpsertEntriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpsertEntriesCall) DoAndReturn(f func(context.Context, int64, []models.Entry) ([]uuid.UUID, error)) *MockRepositoryUpsertEntriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
