// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_handlers_test.go -package=cli -source=handlers.go Handlers
//

// Package cli is a generated GoMock package.
package cli

import (
	reflect "reflect"

	cobra "github.com/spf13/cobra"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// AddCard mocks base method.
func (m *MockHandlers) AddCard(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCard", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCard indicates an expected call of AddCard.
func (mr *MockHandlersMockRecorder) AddCard(cmd, args any) *MockHandlersAddCardCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCard", reflect.TypeOf((*MockHandlers)(nil).AddCard), cmd, args)
	return &MockHandlersAddCardCall{Call: call}
}

// MockHandlersAddCardCall wrap *gomock.Call
type MockHandlersAddCardCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersAddCardCall) Return(arg0 error) *MockHandlersAddCardCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersAddCardCall) Do(f func(*cobra.Command, []string) error) *MockHandlersAddCardCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersAddCardCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersAddCardCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddFile mocks base method.
func (m *MockHandlers) AddFile(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFile", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFile indicates an expected call of AddFile.
func (mr *MockHandlersMockRecorder) AddFile(cmd, args any) *MockHandlersAddFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFile", reflect.TypeOf((*MockHandlers)(nil).AddFile), cmd, args)
	return &MockHandlersAddFileCall{Call: call}
}

// MockHandlersAddFileCall wrap *gomock.Call
type MockHandlersAddFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersAddFileCall) Return(arg0 error) *MockHandlersAddFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersAddFileCall) Do(f func(*cobra.Command, []string) error) *MockHandlersAddFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersAddFileCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersAddFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddPassword mocks base method.
func (m *MockHandlers) AddPassword(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPassword", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPassword indicates an expected call of AddPassword.
func (mr *MockHandlersMockRecorder) AddPassword(cmd, args any) *MockHandlersAddPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPassword", reflect.TypeOf((*MockHandlers)(nil).AddPassword), cmd, args)
	return &MockHandlersAddPasswordCall{Call: call}
}

// MockHandlersAddPasswordCall wrap *gomock.Call
type MockHandlersAddPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersAddPasswordCall) Return(arg0 error) *MockHandlersAddPasswordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersAddPasswordCall) Do(f func(*cobra.Command, []string) error) *MockHandlersAddPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersAddPasswordCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersAddPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddText mocks base method.
func (m *MockHandlers) AddText(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddText", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddText indicates an expected call of AddText.
func (mr *MockHandlersMockRecorder) AddText(cmd, args any) *MockHandlersAddTextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddText", reflect.TypeOf((*MockHandlers)(nil).AddText), cmd, args)
	return &MockHandlersAddTextCall{Call: call}
}

// MockHandlersAddTextCall wrap *gomock.Call
type MockHandlersAddTextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersAddTextCall) Return(arg0 error) *MockHandlersAddTextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersAddTextCall) Do(f func(*cobra.Command, []string) error) *MockHandlersAddTextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersAddTextCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersAddTextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockHandlers) Delete(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHandlersMockRecorder) Delete(cmd, args any) *MockHandlersDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHandlers)(nil).Delete), cmd, args)
	return &MockHandlersDeleteCall{Call: call}
}

// MockHandlersDeleteCall wrap *gomock.Call
type MockHandlersDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersDeleteCall) Return(arg0 error) *MockHandlersDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersDeleteCall) Do(f func(*cobra.Command, []string) error) *MockHandlersDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersDeleteCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockHandlers) Get(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockHandlersMockRecorder) Get(cmd, args any) *MockHandlersGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHandlers)(nil).Get), cmd, args)
	return &MockHandlersGetCall{Call: call}
}

// MockHandlersGetCall wrap *gomock.Call
type MockHandlersGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersGetCall) Return(arg0 error) *MockHandlersGetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersGetCall) Do(f func(*cobra.Command, []string) error) *MockHandlersGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersGetCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockHandlers) List(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockHandlersMockRecorder) List(cmd, args any) *MockHandlersListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHandlers)(nil).List), cmd, args)
	return &MockHandlersListCall{Call: call}
}

// MockHandlersListCall wrap *gomock.Call
type MockHandlersListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersListCall) Return(arg0 error) *MockHandlersListCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersListCall) Do(f func(*cobra.Command, []string) error) *MockHandlersListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersListCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Login mocks base method.
func (m *MockHandlers) Login(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockHandlersMockRecorder) Login(cmd, args any) *MockHandlersLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockHandlers)(nil).Login), cmd, args)
	return &MockHandlersLoginCall{Call: call}
}

// MockHandlersLoginCall wrap *gomock.Call
type MockHandlersLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersLoginCall) Return(arg0 error) *MockHandlersLoginCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersLoginCall) Do(f func(*cobra.Command, []string) error) *MockHandlersLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersLoginCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logout mocks base method.
func (m *MockHandlers) Logout(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockHandlersMockRecorder) Logout(cmd, args any) *MockHandlersLogoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockHandlers)(nil).Logout), cmd, args)
	return &MockHandlersLogoutCall{Call: call}
}

// MockHandlersLogoutCall wrap *gomock.Call
type MockHandlersLogoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersLogoutCall) Return(arg0 error) *MockHandlersLogoutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersLogoutCall) Do(f func(*cobra.Command, []string) error) *MockHandlersLogoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersLogoutCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersLogoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Register mocks base method.
func (m *MockHandlers) Register(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockHandlersMockRecorder) Register(cmd, args any) *MockHandlersRegisterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockHandlers)(nil).Register), cmd, args)
	return &MockHandlersRegisterCall{Call: call}
}

// MockHandlersRegisterCall wrap *gomock.Call
type MockHandlersRegisterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersRegisterCall) Return(arg0 error) *MockHandlersRegisterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersRegisterCall) Do(f func(*cobra.Command, []string) error) *MockHandlersRegisterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersRegisterCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersRegisterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Sync mocks base method.
func (m *MockHandlers) Sync(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockHandlersMockRecorder) Sync(cmd, args any) *MockHandlersSyncCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockHandlers)(nil).Sync), cmd, args)
	return &MockHandlersSyncCall{Call: call}
}

// MockHandlersSyncCall wrap *gomock.Call
type MockHandlersSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersSyncCall) Return(arg0 error) *MockHandlersSyncCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersSyncCall) Do(f func(*cobra.Command, []string) error) *MockHandlersSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersSyncCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCard mocks base method.
func (m *MockHandlers) UpdateCard(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCard", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCard indicates an expected call of UpdateCard.
func (mr *MockHandlersMockRecorder) UpdateCard(cmd, args any) *MockHandlersUpdateCardCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCard", reflect.TypeOf((*MockHandlers)(nil).UpdateCard), cmd, args)
	return &MockHandlersUpdateCardCall{Call: call}
}

// MockHandlersUpdateCardCall wrap *gomock.Call
type MockHandlersUpdateCardCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersUpdateCardCall) Return(arg0 error) *MockHandlersUpdateCardCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersUpdateCardCall) Do(f func(*cobra.Command, []string) error) *MockHandlersUpdateCardCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersUpdateCardCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersUpdateCardCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateFile mocks base method.
func (m *MockHandlers) UpdateFile(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFile indicates an expected call of UpdateFile.
func (mr *MockHandlersMockRecorder) UpdateFile(cmd, args any) *MockHandlersUpdateFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockHandlers)(nil).UpdateFile), cmd, args)
	return &MockHandlersUpdateFileCall{Call: call}
}

// MockHandlersUpdateFileCall wrap *gomock.Call
type MockHandlersUpdateFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersUpdateFileCall) Return(arg0 error) *MockHandlersUpdateFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersUpdateFileCall) Do(f func(*cobra.Command, []string) error) *MockHandlersUpdateFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersUpdateFileCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersUpdateFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdatePassword mocks base method.
func (m *MockHandlers) UpdatePassword(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockHandlersMockRecorder) UpdatePassword(cmd, args any) *MockHandlersUpdatePasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockHandlers)(nil).UpdatePassword), cmd, args)
	return &MockHandlersUpdatePasswordCall{Call: call}
}

// MockHandlersUpdatePasswordCall wrap *gomock.Call
type MockHandlersUpdatePasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersUpdatePasswordCall) Return(arg0 error) *MockHandlersUpdatePasswordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersUpdatePasswordCall) Do(f func(*cobra.Command, []string) error) *MockHandlersUpdatePasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersUpdatePasswordCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersUpdatePasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateText mocks base method.
func (m *MockHandlers) UpdateText(cmd *cobra.Command, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateText", cmd, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateText indicates an expected call of UpdateText.
func (mr *MockHandlersMockRecorder) UpdateText(cmd, args any) *MockHandlersUpdateTextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateText", reflect.TypeOf((*MockHandlers)(nil).UpdateText), cmd, args)
	return &MockHandlersUpdateTextCall{Call: call}
}

// MockHandlersUpdateTextCall wrap *gomock.Call
type MockHandlersUpdateTextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlersUpdateTextCall) Return(arg0 error) *MockHandlersUpdateTextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlersUpdateTextCall) Do(f func(*cobra.Command, []string) error) *MockHandlersUpdateTextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlersUpdateTextCall) DoAndReturn(f func(*cobra.Command, []string) error) *MockHandlersUpdateTextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
