// Code generated by MockGen. DO NOT EDIT.
// Source: secret.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_secret_test.go -package=usecase -source=secret.go LocalSecretStore,SessionReader,VaultRemote
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/georgg2003/skeeper/internal/client/pkg/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockLocalSecretStore is a mock of LocalSecretStore interface.
type MockLocalSecretStore struct {
	ctrl     *gomock.Controller
	recorder *MockLocalSecretStoreMockRecorder
	isgomock struct{}
}

// MockLocalSecretStoreMockRecorder is the mock recorder for MockLocalSecretStore.
type MockLocalSecretStoreMockRecorder struct {
	mock *MockLocalSecretStore
}

// NewMockLocalSecretStore creates a new mock instance.
func NewMockLocalSecretStore(ctrl *gomock.Controller) *MockLocalSecretStore {
	mock := &MockLocalSecretStore{ctrl: ctrl}
	mock.recorder = &MockLocalSecretStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalSecretStore) EXPECT() *MockLocalSecretStoreMockRecorder {
	return m.recorder
}

// EnsureLocalVaultCrypto mocks base method.
func (m *MockLocalSecretStore) EnsureLocalVaultCrypto(ctx context.Context, userID int64) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureLocalVaultCrypto", ctx, userID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EnsureLocalVaultCrypto indicates an expected call of EnsureLocalVaultCrypto.
func (mr *MockLocalSecretStoreMockRecorder) EnsureLocalVaultCrypto(ctx, userID any) *MockLocalSecretStoreEnsureLocalVaultCryptoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureLocalVaultCrypto", reflect.TypeOf((*MockLocalSecretStore)(nil).EnsureLocalVaultCrypto), ctx, userID)
	return &MockLocalSecretStoreEnsureLocalVaultCryptoCall{Call: call}
}

// MockLocalSecretStoreEnsureLocalVaultCryptoCall wrap *gomock.Call
type MockLocalSecretStoreEnsureLocalVaultCryptoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSecretStoreEnsureLocalVaultCryptoCall) Return(salt, masterVerifier []byte, err error) *MockLocalSecretStoreEnsureLocalVaultCryptoCall {
	c.Call = c.Call.Return(salt, masterVerifier, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSecretStoreEnsureLocalVaultCryptoCall) Do(f func(context.Context, int64) ([]byte, []byte, error)) *MockLocalSecretStoreEnsureLocalVaultCryptoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSecretStoreEnsureLocalVaultCryptoCall) DoAndReturn(f func(context.Context, int64) ([]byte, []byte, error)) *MockLocalSecretStoreEnsureLocalVaultCryptoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDirtyEntries mocks base method.
func (m *MockLocalSecretStore) GetDirtyEntries(ctx context.Context, forUserID *int64) ([]models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirtyEntries", ctx, forUserID)
	ret0, _ := ret[0].([]models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirtyEntries indicates an expected call of GetDirtyEntries.
func (mr *MockLocalSecretStoreMockRecorder) GetDirtyEntries(ctx, forUserID any) *MockLocalSecretStoreGetDirtyEntriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirtyEntries", reflect.TypeOf((*MockLocalSecretStore)(nil).GetDirtyEntries), ctx, forUserID)
	return &MockLocalSecretStoreGetDirtyEntriesCall{Call: call}
}

// MockLocalSecretStoreGetDirtyEntriesCall wrap *gomock.Call
type MockLocalSecretStoreGetDirtyEntriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSecretStoreGetDirtyEntriesCall) Return(arg0 []models.Entry, arg1 error) *MockLocalSecretStoreGetDirtyEntriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSecretStoreGetDirtyEntriesCall) Do(f func(context.Context, *int64) ([]models.Entry, error)) *MockLocalSecretStoreGetDirtyEntriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSecretStoreGetDirtyEntriesCall) DoAndReturn(f func(context.Context, *int64) ([]models.Entry, error)) *MockLocalSecretStoreGetDirtyEntriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetEntry mocks base method.
func (m *MockLocalSecretStore) GetEntry(ctx context.Context, id uuid.UUID, forUserID *int64) (models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", ctx, id, forUserID)
	ret0, _ := ret[0].(models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockLocalSecretStoreMockRecorder) GetEntry(ctx, id, forUserID any) *MockLocalSecretStoreGetEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockLocalSecretStore)(nil).GetEntry), ctx, id, forUserID)
	return &MockLocalSecretStoreGetEntryCall{Call: call}
}

// MockLocalSecretStoreGetEntryCall wrap *gomock.Call
type MockLocalSecretStoreGetEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSecretStoreGetEntryCall) Return(arg0 models.Entry, arg1 error) *MockLocalSecretStoreGetEntryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSecretStoreGetEntryCall) Do(f func(context.Context, uuid.UUID, *int64) (models.Entry, error)) *MockLocalSecretStoreGetEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSecretStoreGetEntryCall) DoAndReturn(f func(context.Context, uuid.UUID, *int64) (models.Entry, error)) *MockLocalSecretStoreGetEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLastUpdate mocks base method.
func (m *MockLocalSecretStore) GetLastUpdate(ctx context.Context, forUserID *int64) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUpdate", ctx, forUserID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUpdate indicates an expected call of GetLastUpdate.
func (mr *MockLocalSecretStoreMockRecorder) GetLastUpdate(ctx, forUserID any) *MockLocalSecretStoreGetLastUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUpdate", reflect.TypeOf((*MockLocalSecretStore)(nil).GetLastUpdate), ctx, forUserID)
	return &MockLocalSecretStoreGetLastUpdateCall{Call: call}
}

// MockLocalSecretStoreGetLastUpdateCall wrap *gomock.Call
type MockLocalSecretStoreGetLastUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSecretStoreGetLastUpdateCall) Return(arg0 time.Time, arg1 error) *MockLocalSecretStoreGetLastUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSecretStoreGetLastUpdateCall) Do(f func(context.Context, *int64) (time.Time, error)) *MockLocalSecretStoreGetLastUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSecretStoreGetLastUpdateCall) DoAndReturn(f func(context.Context, *int64) (time.Time, error)) *MockLocalSecretStoreGetLastUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListEntries mocks base method.
func (m *MockLocalSecretStore) ListEntries(ctx context.Context, forUserID *int64) ([]models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", ctx, forUserID)
	ret0, _ := ret[0].([]models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockLocalSecretStoreMockRecorder) ListEntries(ctx, forUserID any) *MockLocalSecretStoreListEntriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntries", reflect.TypeOf((*MockLocalSecretStore)(nil).ListEntries), ctx, forUserID)
	return &MockLocalSecretStoreListEntriesCall{Call: call}
}

// MockLocalSecretStoreListEntriesCall wrap *gomock.Call
type MockLocalSecretStoreListEntriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSecretStoreListEntriesCall) Return(arg0 []models.Entry, arg1 error) *MockLocalSecretStoreListEntriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSecretStoreListEntriesCall) Do(f func(context.Context, *int64) ([]models.Entry, error)) *MockLocalSecretStoreListEntriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSecretStoreListEntriesCall) DoAndReturn(f func(context.Context, *int64) ([]models.Entry, error)) *MockLocalSecretStoreListEntriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkAsSynced mocks base method.
func (m *MockLocalSecretStore) MarkAsSynced(ctx context.Context, id uuid.UUID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsSynced", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsSynced indicates an expected call of MarkAsSynced.
func (mr *MockLocalSecretStoreMockRecorder) MarkAsSynced(ctx, id, userID any) *MockLocalSecretStoreMarkAsSyncedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsSynced", reflect.TypeOf((*MockLocalSecretStore)(nil).MarkAsSynced), ctx, id, userID)
	return &MockLocalSecretStoreMarkAsSyncedCall{Call: call}
}

// MockLocalSecretStoreMarkAsSyncedCall wrap *gomock.Call
type MockLocalSecretStoreMarkAsSyncedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSecretStoreMarkAsSyncedCall) Return(arg0 error) *MockLocalSecretStoreMarkAsSyncedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSecretStoreMarkAsSyncedCall) Do(f func(context.Context, uuid.UUID, int64) error) *MockLocalSecretStoreMarkAsSyncedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSecretStoreMarkAsSyncedCall) DoAndReturn(f func(context.Context, uuid.UUID, int64) error) *MockLocalSecretStoreMarkAsSyncedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReplaceLocalVaultCrypto mocks base method.
func (m *MockLocalSecretStore) ReplaceLocalVaultCrypto(ctx context.Context, userID int64, salt, masterVerifier []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceLocalVaultCrypto", ctx, userID, salt, masterVerifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceLocalVaultCrypto indicates an expected call of ReplaceLocalVaultCrypto.
func (mr *MockLocalSecretStoreMockRecorder) ReplaceLocalVaultCrypto(ctx, userID, salt, masterVerifier any) *MockLocalSecretStoreReplaceLocalVaultCryptoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceLocalVaultCrypto", reflect.TypeOf((*MockLocalSecretStore)(nil).ReplaceLocalVaultCrypto), ctx, userID, salt, masterVerifier)
	return &MockLocalSecretStoreReplaceLocalVaultCryptoCall{Call: call}
}

// MockLocalSecretStoreReplaceLocalVaultCryptoCall wrap *gomock.Call
type MockLocalSecretStoreReplaceLocalVaultCryptoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSecretStoreReplaceLocalVaultCryptoCall) Return(arg0 error) *MockLocalSecretStoreReplaceLocalVaultCryptoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSecretStoreReplaceLocalVaultCryptoCall) Do(f func(context.Context, int64, []byte, []byte) error) *MockLocalSecretStoreReplaceLocalVaultCryptoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSecretStoreReplaceLocalVaultCryptoCall) DoAndReturn(f func(context.Context, int64, []byte, []byte) error) *MockLocalSecretStoreReplaceLocalVaultCryptoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveEntry mocks base method.
func (m *MockLocalSecretStore) SaveEntry(ctx context.Context, e models.Entry, isDirty bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEntry", ctx, e, isDirty)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEntry indicates an expected call of SaveEntry.
func (mr *MockLocalSecretStoreMockRecorder) SaveEntry(ctx, e, isDirty any) *MockLocalSecretStoreSaveEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEntry", reflect.TypeOf((*MockLocalSecretStore)(nil).SaveEntry), ctx, e, isDirty)
	return &MockLocalSecretStoreSaveEntryCall{Call: call}
}

// MockLocalSecretStoreSaveEntryCall wrap *gomock.Call
type MockLocalSecretStoreSaveEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSecretStoreSaveEntryCall) Return(arg0 error) *MockLocalSecretStoreSaveEntryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSecretStoreSaveEntryCall) Do(f func(context.Context, models.Entry, bool) error) *MockLocalSecretStoreSaveEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSecretStoreSaveEntryCall) DoAndReturn(f func(context.Context, models.Entry, bool) error) *MockLocalSecretStoreSaveEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetLocalMasterVerifier mocks base method.
func (m *MockLocalSecretStore) SetLocalMasterVerifier(ctx context.Context, userID int64, masterVerifier []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLocalMasterVerifier", ctx, userID, masterVerifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLocalMasterVerifier indicates an expected call of SetLocalMasterVerifier.
func (mr *MockLocalSecretStoreMockRecorder) SetLocalMasterVerifier(ctx, userID, masterVerifier any) *MockLocalSecretStoreSetLocalMasterVerifierCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLocalMasterVerifier", reflect.TypeOf((*MockLocalSecretStore)(nil).SetLocalMasterVerifier), ctx, userID, masterVerifier)
	return &MockLocalSecretStoreSetLocalMasterVerifierCall{Call: call}
}

// MockLocalSecretStoreSetLocalMasterVerifierCall wrap *gomock.Call
type MockLocalSecretStoreSetLocalMasterVerifierCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSecretStoreSetLocalMasterVerifierCall) Return(arg0 error) *MockLocalSecretStoreSetLocalMasterVerifierCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSecretStoreSetLocalMasterVerifierCall) Do(f func(context.Context, int64, []byte) error) *MockLocalSecretStoreSetLocalMasterVerifierCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSecretStoreSetLocalMasterVerifierCall) DoAndReturn(f func(context.Context, int64, []byte) error) *MockLocalSecretStoreSetLocalMasterVerifierCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionReader is a mock of SessionReader interface.
type MockSessionReader struct {
	ctrl     *gomock.Controller
	recorder *MockSessionReaderMockRecorder
	isgomock struct{}
}

// MockSessionReaderMockRecorder is the mock recorder for MockSessionReader.
type MockSessionReaderMockRecorder struct {
	mock *MockSessionReader
}

// NewMockSessionReader creates a new mock instance.
func NewMockSessionReader(ctrl *gomock.Controller) *MockSessionReader {
	mock := &MockSessionReader{ctrl: ctrl}
	mock.recorder = &MockSessionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionReader) EXPECT() *MockSessionReaderMockRecorder {
	return m.recorder
}

// GetSession mocks base method.
func (m *MockSessionReader) GetSession(ctx context.Context) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionReaderMockRecorder) GetSession(ctx any) *MockSessionReaderGetSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionReader)(nil).GetSession), ctx)
	return &MockSessionReaderGetSessionCall{Call: call}
}

// MockSessionReaderGetSessionCall wrap *gomock.Call
type MockSessionReaderGetSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionReaderGetSessionCall) Return(arg0 *models.Session, arg1 error) *MockSessionReaderGetSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionReaderGetSessionCall) Do(f func(context.Context) (*models.Session, error)) *MockSessionReaderGetSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionReaderGetSessionCall) DoAndReturn(f func(context.Context) (*models.Session, error)) *MockSessionReaderGetSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockVaultRemote is a mock of VaultRemote interface.
type MockVaultRemote struct {
	ctrl     *gomock.Controller
	recorder *MockVaultRemoteMockRecorder
	isgomock struct{}
}

// MockVaultRemoteMockRecorder is the mock recorder for MockVaultRemote.
type MockVaultRemoteMockRecorder struct {
	mock *MockVaultRemote
}

// NewMockVaultRemote creates a new mock instance.
func NewMockVaultRemote(ctrl *gomock.Controller) *MockVaultRemote {
	mock := &MockVaultRemote{ctrl: ctrl}
	mock.recorder = &MockVaultRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultRemote) EXPECT() *MockVaultRemoteMockRecorder {
	return m.recorder
}

// GetVaultCrypto mocks base method.
func (m *MockVaultRemote) GetVaultCrypto(ctx context.Context) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVaultCrypto", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVaultCrypto indicates an expected call of GetVaultCrypto.
func (mr *MockVaultRemoteMockRecorder) GetVaultCrypto(ctx any) *MockVaultRemoteGetVaultCryptoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVaultCrypto", reflect.TypeOf((*MockVaultRemote)(nil).GetVaultCrypto), ctx)
	return &MockVaultRemoteGetVaultCryptoCall{Call: call}
}

// MockVaultRemoteGetVaultCryptoCall wrap *gomock.Call
type MockVaultRemoteGetVaultCryptoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVaultRemoteGetVaultCryptoCall) Return(kdfSalt, masterVerifier []byte, err error) *MockVaultRemoteGetVaultCryptoCall {
	c.Call = c.Call.Return(kdfSalt, masterVerifier, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVaultRemoteGetVaultCryptoCall) Do(f func(context.Context) ([]byte, []byte, error)) *MockVaultRemoteGetVaultCryptoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVaultRemoteGetVaultCryptoCall) DoAndReturn(f func(context.Context) ([]byte, []byte, error)) *MockVaultRemoteGetVaultCryptoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutVaultCrypto mocks base method.
func (m *MockVaultRemote) PutVaultCrypto(ctx context.Context, kdfSalt, masterVerifier []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutVaultCrypto", ctx, kdfSalt, masterVerifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutVaultCrypto indicates an expected call of PutVaultCrypto.
func (mr *MockVaultRemoteMockRecorder) PutVaultCrypto(ctx, kdfSalt, masterVerifier any) *MockVaultRemotePutVaultCryptoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutVaultCrypto", reflect.TypeOf((*MockVaultRemote)(nil).PutVaultCrypto), ctx, kdfSalt, masterVerifier)
	return &MockVaultRemotePutVaultCryptoCall{Call: call}
}

// MockVaultRemotePutVaultCryptoCall wrap *gomock.Call
type MockVaultRemotePutVaultCryptoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVaultRemotePutVaultCryptoCall) Return(arg0 error) *MockVaultRemotePutVaultCryptoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVaultRemotePutVaultCryptoCall) Do(f func(context.Context, []byte, []byte) error) *MockVaultRemotePutVaultCryptoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVaultRemotePutVaultCryptoCall) DoAndReturn(f func(context.Context, []byte, []byte) error) *MockVaultRemotePutVaultCryptoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
