// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_auth_test.go -package=usecase -source=auth.go SessionStore,RemoteAuthenticator
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	models "github.com/georgg2003/skeeper/internal/client/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// ClearSession mocks base method.
func (m *MockSessionStore) ClearSession(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSession", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSession indicates an expected call of ClearSession.
func (mr *MockSessionStoreMockRecorder) ClearSession(ctx any) *MockSessionStoreClearSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSession", reflect.TypeOf((*MockSessionStore)(nil).ClearSession), ctx)
	return &MockSessionStoreClearSessionCall{Call: call}
}

// MockSessionStoreClearSessionCall wrap *gomock.Call
type MockSessionStoreClearSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionStoreClearSessionCall) Return(arg0 error) *MockSessionStoreClearSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionStoreClearSessionCall) Do(f func(context.Context) error) *MockSessionStoreClearSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionStoreClearSessionCall) DoAndReturn(f func(context.Context) error) *MockSessionStoreClearSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSession mocks base method.
func (m *MockSessionStore) GetSession(ctx context.Context) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionStoreMockRecorder) GetSession(ctx any) *MockSessionStoreGetSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionStore)(nil).GetSession), ctx)
	return &MockSessionStoreGetSessionCall{Call: call}
}

// MockSessionStoreGetSessionCall wrap *gomock.Call
type MockSessionStoreGetSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionStoreGetSessionCall) Return(arg0 *models.Session, arg1 error) *MockSessionStoreGetSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionStoreGetSessionCall) Do(f func(context.Context) (*models.Session, error)) *MockSessionStoreGetSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionStoreGetSessionCall) DoAndReturn(f func(context.Context) (*models.Session, error)) *MockSessionStoreGetSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveSession mocks base method.
func (m *MockSessionStore) SaveSession(ctx context.Context, s models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockSessionStoreMockRecorder) SaveSession(ctx, s any) *MockSessionStoreSaveSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockSessionStore)(nil).SaveSession), ctx, s)
	return &MockSessionStoreSaveSessionCall{Call: call}
}

// MockSessionStoreSaveSessionCall wrap *gomock.Call
type MockSessionStoreSaveSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionStoreSaveSessionCall) Return(arg0 error) *MockSessionStoreSaveSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionStoreSaveSessionCall) Do(f func(context.Context, models.Session) error) *MockSessionStoreSaveSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionStoreSaveSessionCall) DoAndReturn(f func(context.Context, models.Session) error) *MockSessionStoreSaveSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRemoteAuthenticator is a mock of RemoteAuthenticator interface.
type MockRemoteAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteAuthenticatorMockRecorder
	isgomock struct{}
}

// MockRemoteAuthenticatorMockRecorder is the mock recorder for MockRemoteAuthenticator.
type MockRemoteAuthenticatorMockRecorder struct {
	mock *MockRemoteAuthenticator
}

// NewMockRemoteAuthenticator creates a new mock instance.
func NewMockRemoteAuthenticator(ctrl *gomock.Controller) *MockRemoteAuthenticator {
	mock := &MockRemoteAuthenticator{ctrl: ctrl}
	mock.recorder = &MockRemoteAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteAuthenticator) EXPECT() *MockRemoteAuthenticatorMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockRemoteAuthenticator) CreateUser(ctx context.Context, email, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRemoteAuthenticatorMockRecorder) CreateUser(ctx, email, password any) *MockRemoteAuthenticatorCreateUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRemoteAuthenticator)(nil).CreateUser), ctx, email, password)
	return &MockRemoteAuthenticatorCreateUserCall{Call: call}
}

// MockRemoteAuthenticatorCreateUserCall wrap *gomock.Call
type MockRemoteAuthenticatorCreateUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRemoteAuthenticatorCreateUserCall) Return(arg0 error) *MockRemoteAuthenticatorCreateUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRemoteAuthenticatorCreateUserCall) Do(f func(context.Context, string, string) error) *MockRemoteAuthenticatorCreateUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRemoteAuthenticatorCreateUserCall) DoAndReturn(f func(context.Context, string, string) error) *MockRemoteAuthenticatorCreateUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Login mocks base method.
func (m *MockRemoteAuthenticator) Login(ctx context.Context, login, password string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, login, password)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockRemoteAuthenticatorMockRecorder) Login(ctx, login, password any) *MockRemoteAuthenticatorLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockRemoteAuthenticator)(nil).Login), ctx, login, password)
	return &MockRemoteAuthenticatorLoginCall{Call: call}
}

// MockRemoteAuthenticatorLoginCall wrap *gomock.Call
type MockRemoteAuthenticatorLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRemoteAuthenticatorLoginCall) Return(arg0 *models.Session, arg1 error) *MockRemoteAuthenticatorLoginCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRemoteAuthenticatorLoginCall) Do(f func(context.Context, string, string) (*models.Session, error)) *MockRemoteAuthenticatorLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRemoteAuthenticatorLoginCall) DoAndReturn(f func(context.Context, string, string) (*models.Session, error)) *MockRemoteAuthenticatorLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Refresh mocks base method.
func (m *MockRemoteAuthenticator) Refresh(ctx context.Context, refreshToken string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockRemoteAuthenticatorMockRecorder) Refresh(ctx, refreshToken any) *MockRemoteAuthenticatorRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockRemoteAuthenticator)(nil).Refresh), ctx, refreshToken)
	return &MockRemoteAuthenticatorRefreshCall{Call: call}
}

// MockRemoteAuthenticatorRefreshCall wrap *gomock.Call
type MockRemoteAuthenticatorRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRemoteAuthenticatorRefreshCall) Return(arg0 *models.Session, arg1 error) *MockRemoteAuthenticatorRefreshCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRemoteAuthenticatorRefreshCall) Do(f func(context.Context, string) (*models.Session, error)) *MockRemoteAuthenticatorRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRemoteAuthenticatorRefreshCall) DoAndReturn(f func(context.Context, string) (*models.Session, error)) *MockRemoteAuthenticatorRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
