// Code generated by MockGen. DO NOT EDIT.
// Source: token.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_token_test.go -package=usecase -source=token.go AuthProvider
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	models "github.com/georgg2003/skeeper/internal/client/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthProvider is a mock of AuthProvider interface.
type MockAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuthProviderMockRecorder
	isgomock struct{}
}

// MockAuthProviderMockRecorder is the mock recorder for MockAuthProvider.
type MockAuthProviderMockRecorder struct {
	mock *MockAuthProvider
}

// NewMockAuthProvider creates a new mock instance.
func NewMockAuthProvider(ctrl *gomock.Controller) *MockAuthProvider {
	mock := &MockAuthProvider{ctrl: ctrl}
	mock.recorder = &MockAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthProvider) EXPECT() *MockAuthProviderMockRecorder {
	return m.recorder
}

// Refresh mocks base method.
func (m *MockAuthProvider) Refresh(ctx context.Context, refreshToken string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthProviderMockRecorder) Refresh(ctx, refreshToken any) *MockAuthProviderRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthProvider)(nil).Refresh), ctx, refreshToken)
	return &MockAuthProviderRefreshCall{Call: call}
}

// MockAuthProviderRefreshCall wrap *gomock.Call
type MockAuthProviderRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthProviderRefreshCall) Return(arg0 *models.Session, arg1 error) *MockAuthProviderRefreshCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthProviderRefreshCall) Do(f func(context.Context, string) (*models.Session, error)) *MockAuthProviderRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthProviderRefreshCall) DoAndReturn(f func(context.Context, string) (*models.Session, error)) *MockAuthProviderRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
