// Code generated by MockGen. DO NOT EDIT.
// Source: sync.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_sync_test.go -package=usecase -source=sync.go LocalSyncRepo,RemoteSyncRepo
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/georgg2003/skeeper/internal/client/pkg/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockLocalSyncRepo is a mock of LocalSyncRepo interface.
type MockLocalSyncRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLocalSyncRepoMockRecorder
	isgomock struct{}
}

// MockLocalSyncRepoMockRecorder is the mock recorder for MockLocalSyncRepo.
type MockLocalSyncRepoMockRecorder struct {
	mock *MockLocalSyncRepo
}

// NewMockLocalSyncRepo creates a new mock instance.
func NewMockLocalSyncRepo(ctrl *gomock.Controller) *MockLocalSyncRepo {
	mock := &MockLocalSyncRepo{ctrl: ctrl}
	mock.recorder = &MockLocalSyncRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalSyncRepo) EXPECT() *MockLocalSyncRepoMockRecorder {
	return m.recorder
}

// GetDirtyEntries mocks base method.
func (m *MockLocalSyncRepo) GetDirtyEntries(ctx context.Context, forUserID *int64) ([]models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirtyEntries", ctx, forUserID)
	ret0, _ := ret[0].([]models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirtyEntries indicates an expected call of GetDirtyEntries.
func (mr *MockLocalSyncRepoMockRecorder) GetDirtyEntries(ctx, forUserID any) *MockLocalSyncRepoGetDirtyEntriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirtyEntries", reflect.TypeOf((*MockLocalSyncRepo)(nil).GetDirtyEntries), ctx, forUserID)
	return &MockLocalSyncRepoGetDirtyEntriesCall{Call: call}
}

// MockLocalSyncRepoGetDirtyEntriesCall wrap *gomock.Call
type MockLocalSyncRepoGetDirtyEntriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSyncRepoGetDirtyEntriesCall) Return(arg0 []models.Entry, arg1 error) *MockLocalSyncRepoGetDirtyEntriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSyncRepoGetDirtyEntriesCall) Do(f func(context.Context, *int64) ([]models.Entry, error)) *MockLocalSyncRepoGetDirtyEntriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSyncRepoGetDirtyEntriesCall) DoAndReturn(f func(context.Context, *int64) ([]models.Entry, error)) *MockLocalSyncRepoGetDirtyEntriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLastUpdate mocks base method.
func (m *MockLocalSyncRepo) GetLastUpdate(ctx context.Context, forUserID *int64) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUpdate", ctx, forUserID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUpdate indicates an expected call of GetLastUpdate.
func (mr *MockLocalSyncRepoMockRecorder) GetLastUpdate(ctx, forUserID any) *MockLocalSyncRepoGetLastUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUpdate", reflect.TypeOf((*MockLocalSyncRepo)(nil).GetLastUpdate), ctx, forUserID)
	return &MockLocalSyncRepoGetLastUpdateCall{Call: call}
}

// MockLocalSyncRepoGetLastUpdateCall wrap *gomock.Call
type MockLocalSyncRepoGetLastUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSyncRepoGetLastUpdateCall) Return(arg0 time.Time, arg1 error) *MockLocalSyncRepoGetLastUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSyncRepoGetLastUpdateCall) Do(f func(context.Context, *int64) (time.Time, error)) *MockLocalSyncRepoGetLastUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSyncRepoGetLastUpdateCall) DoAndReturn(f func(context.Context, *int64) (time.Time, error)) *MockLocalSyncRepoGetLastUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PersistSyncResult mocks base method.
func (m *MockLocalSyncRepo) PersistSyncResult(ctx context.Context, userID int64, updates, dirty []models.Entry, applied map[uuid.UUID]struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistSyncResult", ctx, userID, updates, dirty, applied)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistSyncResult indicates an expected call of PersistSyncResult.
func (mr *MockLocalSyncRepoMockRecorder) PersistSyncResult(ctx, userID, updates, dirty, applied any) *MockLocalSyncRepoPersistSyncResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistSyncResult", reflect.TypeOf((*MockLocalSyncRepo)(nil).PersistSyncResult), ctx, userID, updates, dirty, applied)
	return &MockLocalSyncRepoPersistSyncResultCall{Call: call}
}

// MockLocalSyncRepoPersistSyncResultCall wrap *gomock.Call
type MockLocalSyncRepoPersistSyncResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSyncRepoPersistSyncResultCall) Return(arg0 error) *MockLocalSyncRepoPersistSyncResultCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSyncRepoPersistSyncResultCall) Do(f func(context.Context, int64, []models.Entry, []models.Entry, map[uuid.UUID]struct{}) error) *MockLocalSyncRepoPersistSyncResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSyncRepoPersistSyncResultCall) DoAndReturn(f func(context.Context, int64, []models.Entry, []models.Entry, map[uuid.UUID]struct{}) error) *MockLocalSyncRepoPersistSyncResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveEntry mocks base method.
func (m *MockLocalSyncRepo) SaveEntry(ctx context.Context, e models.Entry, isDirty bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEntry", ctx, e, isDirty)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEntry indicates an expected call of SaveEntry.
func (mr *MockLocalSyncRepoMockRecorder) SaveEntry(ctx, e, isDirty any) *MockLocalSyncRepoSaveEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEntry", reflect.TypeOf((*MockLocalSyncRepo)(nil).SaveEntry), ctx, e, isDirty)
	return &MockLocalSyncRepoSaveEntryCall{Call: call}
}

// MockLocalSyncRepoSaveEntryCall wrap *gomock.Call
type MockLocalSyncRepoSaveEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLocalSyncRepoSaveEntryCall) Return(arg0 error) *MockLocalSyncRepoSaveEntryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLocalSyncRepoSaveEntryCall) Do(f func(context.Context, models.Entry, bool) error) *MockLocalSyncRepoSaveEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLocalSyncRepoSaveEntryCall) DoAndReturn(f func(context.Context, models.Entry, bool) error) *MockLocalSyncRepoSaveEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRemoteSyncRepo is a mock of RemoteSyncRepo interface.
type MockRemoteSyncRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteSyncRepoMockRecorder
	isgomock struct{}
}

// MockRemoteSyncRepoMockRecorder is the mock recorder for MockRemoteSyncRepo.
type MockRemoteSyncRepoMockRecorder struct {
	mock *MockRemoteSyncRepo
}

// NewMockRemoteSyncRepo creates a new mock instance.
func NewMockRemoteSyncRepo(ctrl *gomock.Controller) *MockRemoteSyncRepo {
	mock := &MockRemoteSyncRepo{ctrl: ctrl}
	mock.recorder = &MockRemoteSyncRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteSyncRepo) EXPECT() *MockRemoteSyncRepoMockRecorder {
	return m.recorder
}

// Sync mocks base method.
func (m *MockRemoteSyncRepo) Sync(ctx context.Context, entries []models.Entry, lastUpdate time.Time) ([]models.Entry, []uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, entries, lastUpdate)
	ret0, _ := ret[0].([]models.Entry)
	ret1, _ := ret[1].([]uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Sync indicates an expected call of Sync.
func (mr *MockRemoteSyncRepoMockRecorder) Sync(ctx, entries, lastUpdate any) *MockRemoteSyncRepoSyncCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockRemoteSyncRepo)(nil).Sync), ctx, entries, lastUpdate)
	return &MockRemoteSyncRepoSyncCall{Call: call}
}

// MockRemoteSyncRepoSyncCall wrap *gomock.Call
type MockRemoteSyncRepoSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRemoteSyncRepoSyncCall) Return(arg0 []models.Entry, arg1 []uuid.UUID, arg2 error) *MockRemoteSyncRepoSyncCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRemoteSyncRepoSyncCall) Do(f func(context.Context, []models.Entry, time.Time) ([]models.Entry, []uuid.UUID, error)) *MockRemoteSyncRepoSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRemoteSyncRepoSyncCall) DoAndReturn(f func(context.Context, []models.Entry, time.Time) ([]models.Entry, []uuid.UUID, error)) *MockRemoteSyncRepoSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
