// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_repository_test.go -package=usecase -source=usecase.go Repository
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	models "github.com/georgg2003/skeeper/internal/auther/pkg/models"
	jwthelper "github.com/georgg2003/skeeper/pkg/jwthelper"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepository) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRepositoryMockRecorder) Close() *MockRepositoryCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepository)(nil).Close))
	return &MockRepositoryCloseCall{Call: call}
}

// MockRepositoryCloseCall wrap *gomock.Call
type MockRepositoryCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCloseCall) Return() *MockRepositoryCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCloseCall) Do(f func()) *MockRepositoryCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCloseCall) DoAndReturn(f func()) *MockRepositoryCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InsertUser mocks base method.
func (m *MockRepository) InsertUser(arg0 context.Context, arg1 models.DBUserCredentials) (models.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", arg0, arg1)
	ret0, _ := ret[0].(models.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockRepositoryMockRecorder) InsertUser(arg0, arg1 any) *MockRepositoryInsertUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockRepository)(nil).InsertUser), arg0, arg1)
	return &MockRepositoryInsertUserCall{Call: call}
}

// MockRepositoryInsertUserCall wrap *gomock.Call
type MockRepositoryInsertUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryInsertUserCall) Return(arg0 models.UserInfo, arg1 error) *MockRepositoryInsertUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryInsertUserCall) Do(f func(context.Context, models.DBUserCredentials) (models.UserInfo, error)) *MockRepositoryInsertUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryInsertUserCall) DoAndReturn(f func(context.Context, models.DBUserCredentials) (models.UserInfo, error)) *MockRepositoryInsertUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReplaceUserRefreshTokens mocks base method.
func (m *MockRepository) ReplaceUserRefreshTokens(ctx context.Context, userID int64, pair jwthelper.TokenPair) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceUserRefreshTokens", ctx, userID, pair)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceUserRefreshTokens indicates an expected call of ReplaceUserRefreshTokens.
func (mr *MockRepositoryMockRecorder) ReplaceUserRefreshTokens(ctx, userID, pair any) *MockRepositoryReplaceUserRefreshTokensCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceUserRefreshTokens", reflect.TypeOf((*MockRepository)(nil).ReplaceUserRefreshTokens), ctx, userID, pair)
	return &MockRepositoryReplaceUserRefreshTokensCall{Call: call}
}

// MockRepositoryReplaceUserRefreshTokensCall wrap *gomock.Call
type MockRepositoryReplaceUserRefreshTokensCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryReplaceUserRefreshTokensCall) Return(arg0 error) *MockRepositoryReplaceUserRefreshTokensCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryReplaceUserRefreshTokensCall) Do(f func(context.Context, int64, jwthelper.TokenPair) error) *MockRepositoryReplaceUserRefreshTokensCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryReplaceUserRefreshTokensCall) DoAndReturn(f func(context.Context, int64, jwthelper.TokenPair) error) *MockRepositoryReplaceUserRefreshTokensCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RotateRefreshToken mocks base method.
func (m *MockRepository) RotateRefreshToken(ctx context.Context, refreshPlain string, mint func(int64) (jwthelper.TokenPair, error)) (jwthelper.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, refreshPlain, mint)
	ret0, _ := ret[0].(jwthelper.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MockRepositoryMockRecorder) RotateRefreshToken(ctx, refreshPlain, mint any) *MockRepositoryRotateRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MockRepository)(nil).RotateRefreshToken), ctx, refreshPlain, mint)
	return &MockRepositoryRotateRefreshTokenCall{Call: call}
}

// MockRepositoryRotateRefreshTokenCall wrap *gomock.Call
type MockRepositoryRotateRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryRotateRefreshTokenCall) Return(arg0 jwthelper.TokenPair, arg1 error) *MockRepositoryRotateRefreshTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryRotateRefreshTokenCall) Do(f func(context.Context, string, func(int64) (jwthelper.TokenPair, error)) (jwthelper.TokenPair, error)) *MockRepositoryRotateRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryRotateRefreshTokenCall) DoAndReturn(f func(context.Context, string, func(int64) (jwthelper.TokenPair, error)) (jwthelper.TokenPair, error)) *MockRepositoryRotateRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SelectUserByEmail mocks base method.
func (m *MockRepository) SelectUserByEmail(arg0 context.Context, arg1 string) (models.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(models.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserByEmail indicates an expected call of SelectUserByEmail.
func (mr *MockRepositoryMockRecorder) SelectUserByEmail(arg0, arg1 any) *MockRepositorySelectUserByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUserByEmail", reflect.TypeOf((*MockRepository)(nil).SelectUserByEmail), arg0, arg1)
	return &MockRepositorySelectUserByEmailCall{Call: call}
}

// MockRepositorySelectUserByEmailCall wrap *gomock.Call
type MockRepositorySelectUserByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySelectUserByEmailCall) Return(arg0 models.UserInfo, arg1 error) *MockRepositorySelectUserByEmailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySelectUserByEmailCall) Do(f func(context.Context, string) (models.UserInfo, error)) *MockRepositorySelectUserByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySelectUserByEmailCall) DoAndReturn(f func(context.Context, string) (models.UserInfo, error)) *MockRepositorySelectUserByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
