// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_usecase_test.go -package=delivery -source=delivery.go UseCase
//

// Package delivery is a generated GoMock package.
package delivery

import (
	context "context"
	reflect "reflect"

	models "github.com/georgg2003/skeeper/internal/auther/pkg/models"
	jwthelper "github.com/georgg2003/skeeper/pkg/jwthelper"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUseCase) CreateUser(arg0 context.Context, arg1 models.UserCredentials) (models.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(models.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUseCaseMockRecorder) CreateUser(arg0, arg1 any) *MockUseCaseCreateUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUseCase)(nil).CreateUser), arg0, arg1)
	return &MockUseCaseCreateUserCall{Call: call}
}

// MockUseCaseCreateUserCall wrap *gomock.Call
type MockUseCaseCreateUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUseCaseCreateUserCall) Return(arg0 models.UserInfo, arg1 error) *MockUseCaseCreateUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUseCaseCreateUserCall) Do(f func(context.Context, models.UserCredentials) (models.UserInfo, error)) *MockUseCaseCreateUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUseCaseCreateUserCall) DoAndReturn(f func(context.Context, models.UserCredentials) (models.UserInfo, error)) *MockUseCaseCreateUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoginUser mocks base method.
func (m *MockUseCase) LoginUser(arg0 context.Context, arg1 models.UserCredentials) (models.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", arg0, arg1)
	ret0, _ := ret[0].(models.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockUseCaseMockRecorder) LoginUser(arg0, arg1 any) *MockUseCaseLoginUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockUseCase)(nil).LoginUser), arg0, arg1)
	return &MockUseCaseLoginUserCall{Call: call}
}

// MockUseCaseLoginUserCall wrap *gomock.Call
type MockUseCaseLoginUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUseCaseLoginUserCall) Return(arg0 models.LoginResponse, arg1 error) *MockUseCaseLoginUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUseCaseLoginUserCall) Do(f func(context.Context, models.UserCredentials) (models.LoginResponse, error)) *MockUseCaseLoginUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUseCaseLoginUserCall) DoAndReturn(f func(context.Context, models.UserCredentials) (models.LoginResponse, error)) *MockUseCaseLoginUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RotateToken mocks base method.
func (m *MockUseCase) RotateToken(ctx context.Context, refreshToken string) (jwthelper.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateToken", ctx, refreshToken)
	ret0, _ := ret[0].(jwthelper.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateToken indicates an expected call of RotateToken.
func (mr *MockUseCaseMockRecorder) RotateToken(ctx, refreshToken any) *MockUseCaseRotateTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateToken", reflect.TypeOf((*MockUseCase)(nil).RotateToken), ctx, refreshToken)
	return &MockUseCaseRotateTokenCall{Call: call}
}

// MockUseCaseRotateTokenCall wrap *gomock.Call
type MockUseCaseRotateTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUseCaseRotateTokenCall) Return(arg0 jwthelper.TokenPair, arg1 error) *MockUseCaseRotateTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUseCaseRotateTokenCall) Do(f func(context.Context, string) (jwthelper.TokenPair, error)) *MockUseCaseRotateTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUseCaseRotateTokenCall) DoAndReturn(f func(context.Context, string) (jwthelper.TokenPair, error)) *MockUseCaseRotateTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
