// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_ports_test.go -package=delivery -source=ports.go AuthCommands,SecretCommands,SyncCommands
//

// Package delivery is a generated GoMock package.
package delivery

import (
	context "context"
	reflect "reflect"

	models "github.com/georgg2003/skeeper/internal/client/pkg/models"
	usecase "github.com/georgg2003/skeeper/internal/client/usecase"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthCommands is a mock of AuthCommands interface.
type MockAuthCommands struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCommandsMockRecorder
	isgomock struct{}
}

// MockAuthCommandsMockRecorder is the mock recorder for MockAuthCommands.
type MockAuthCommandsMockRecorder struct {
	mock *MockAuthCommands
}

// NewMockAuthCommands creates a new mock instance.
func NewMockAuthCommands(ctrl *gomock.Controller) *MockAuthCommands {
	mock := &MockAuthCommands{ctrl: ctrl}
	mock.recorder = &MockAuthCommandsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCommands) EXPECT() *MockAuthCommandsMockRecorder {
	return m.recorder
}

// GetValidToken mocks base method.
func (m *MockAuthCommands) GetValidToken(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidToken", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidToken indicates an expected call of GetValidToken.
func (mr *MockAuthCommandsMockRecorder) GetValidToken(ctx any) *MockAuthCommandsGetValidTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidToken", reflect.TypeOf((*MockAuthCommands)(nil).GetValidToken), ctx)
	return &MockAuthCommandsGetValidTokenCall{Call: call}
}

// MockAuthCommandsGetValidTokenCall wrap *gomock.Call
type MockAuthCommandsGetValidTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthCommandsGetValidTokenCall) Return(arg0 string, arg1 error) *MockAuthCommandsGetValidTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthCommandsGetValidTokenCall) Do(f func(context.Context) (string, error)) *MockAuthCommandsGetValidTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthCommandsGetValidTokenCall) DoAndReturn(f func(context.Context) (string, error)) *MockAuthCommandsGetValidTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Login mocks base method.
func (m *MockAuthCommands) Login(ctx context.Context, login, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, login, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockAuthCommandsMockRecorder) Login(ctx, login, password any) *MockAuthCommandsLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthCommands)(nil).Login), ctx, login, password)
	return &MockAuthCommandsLoginCall{Call: call}
}

// MockAuthCommandsLoginCall wrap *gomock.Call
type MockAuthCommandsLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthCommandsLoginCall) Return(arg0 error) *MockAuthCommandsLoginCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthCommandsLoginCall) Do(f func(context.Context, string, string) error) *MockAuthCommandsLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthCommandsLoginCall) DoAndReturn(f func(context.Context, string, string) error) *MockAuthCommandsLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logout mocks base method.
func (m *MockAuthCommands) Logout(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthCommandsMockRecorder) Logout(ctx any) *MockAuthCommandsLogoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthCommands)(nil).Logout), ctx)
	return &MockAuthCommandsLogoutCall{Call: call}
}

// MockAuthCommandsLogoutCall wrap *gomock.Call
type MockAuthCommandsLogoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthCommandsLogoutCall) Return(arg0 error) *MockAuthCommandsLogoutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthCommandsLogoutCall) Do(f func(context.Context) error) *MockAuthCommandsLogoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthCommandsLogoutCall) DoAndReturn(f func(context.Context) error) *MockAuthCommandsLogoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Register mocks base method.
func (m *MockAuthCommands) Register(ctx context.Context, email, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockAuthCommandsMockRecorder) Register(ctx, email, password any) *MockAuthCommandsRegisterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthCommands)(nil).Register), ctx, email, password)
	return &MockAuthCommandsRegisterCall{Call: call}
}

// MockAuthCommandsRegisterCall wrap *gomock.Call
type MockAuthCommandsRegisterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthCommandsRegisterCall) Return(arg0 error) *MockAuthCommandsRegisterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthCommandsRegisterCall) Do(f func(context.Context, string, string) error) *MockAuthCommandsRegisterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthCommandsRegisterCall) DoAndReturn(f func(context.Context, string, string) error) *MockAuthCommandsRegisterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSecretCommands is a mock of SecretCommands interface.
type MockSecretCommands struct {
	ctrl     *gomock.Controller
	recorder *MockSecretCommandsMockRecorder
	isgomock struct{}
}

// MockSecretCommandsMockRecorder is the mock recorder for MockSecretCommands.
type MockSecretCommandsMockRecorder struct {
	mock *MockSecretCommands
}

// NewMockSecretCommands creates a new mock instance.
func NewMockSecretCommands(ctrl *gomock.Controller) *MockSecretCommands {
	mock := &MockSecretCommands{ctrl: ctrl}
	mock.recorder = &MockSecretCommandsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretCommands) EXPECT() *MockSecretCommandsMockRecorder {
	return m.recorder
}

// DeleteEntry mocks base method.
func (m *MockSecretCommands) DeleteEntry(ctx context.Context, id uuid.UUID, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntry", ctx, id, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry.
func (mr *MockSecretCommandsMockRecorder) DeleteEntry(ctx, id, masterPass any) *MockSecretCommandsDeleteEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockSecretCommands)(nil).DeleteEntry), ctx, id, masterPass)
	return &MockSecretCommandsDeleteEntryCall{Call: call}
}

// MockSecretCommandsDeleteEntryCall wrap *gomock.Call
type MockSecretCommandsDeleteEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsDeleteEntryCall) Return(arg0 error) *MockSecretCommandsDeleteEntryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsDeleteEntryCall) Do(f func(context.Context, uuid.UUID, string) error) *MockSecretCommandsDeleteEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsDeleteEntryCall) DoAndReturn(f func(context.Context, uuid.UUID, string) error) *MockSecretCommandsDeleteEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDecryptedEntry mocks base method.
func (m *MockSecretCommands) GetDecryptedEntry(ctx context.Context, id uuid.UUID, masterPass string) ([]byte, *usecase.EntryMetadata, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDecryptedEntry", ctx, id, masterPass)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*usecase.EntryMetadata)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDecryptedEntry indicates an expected call of GetDecryptedEntry.
func (mr *MockSecretCommandsMockRecorder) GetDecryptedEntry(ctx, id, masterPass any) *MockSecretCommandsGetDecryptedEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDecryptedEntry", reflect.TypeOf((*MockSecretCommands)(nil).GetDecryptedEntry), ctx, id, masterPass)
	return &MockSecretCommandsGetDecryptedEntryCall{Call: call}
}

// MockSecretCommandsGetDecryptedEntryCall wrap *gomock.Call
type MockSecretCommandsGetDecryptedEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsGetDecryptedEntryCall) Return(arg0 []byte, arg1 *usecase.EntryMetadata, arg2 string, arg3 error) *MockSecretCommandsGetDecryptedEntryCall {
	c.Call = c.Call.Return(arg0, arg1, arg2, arg3)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsGetDecryptedEntryCall) Do(f func(context.Context, uuid.UUID, string) ([]byte, *usecase.EntryMetadata, string, error)) *MockSecretCommandsGetDecryptedEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsGetDecryptedEntryCall) DoAndReturn(f func(context.Context, uuid.UUID, string) ([]byte, *usecase.EntryMetadata, string, error)) *MockSecretCommandsGetDecryptedEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLocalEntry mocks base method.
func (m *MockSecretCommands) GetLocalEntry(ctx context.Context, id uuid.UUID) (models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalEntry", ctx, id)
	ret0, _ := ret[0].(models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalEntry indicates an expected call of GetLocalEntry.
func (mr *MockSecretCommandsMockRecorder) GetLocalEntry(ctx, id any) *MockSecretCommandsGetLocalEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalEntry", reflect.TypeOf((*MockSecretCommands)(nil).GetLocalEntry), ctx, id)
	return &MockSecretCommandsGetLocalEntryCall{Call: call}
}

// MockSecretCommandsGetLocalEntryCall wrap *gomock.Call
type MockSecretCommandsGetLocalEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsGetLocalEntryCall) Return(arg0 models.Entry, arg1 error) *MockSecretCommandsGetLocalEntryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsGetLocalEntryCall) Do(f func(context.Context, uuid.UUID) (models.Entry, error)) *MockSecretCommandsGetLocalEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsGetLocalEntryCall) DoAndReturn(f func(context.Context, uuid.UUID) (models.Entry, error)) *MockSecretCommandsGetLocalEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListLocal mocks base method.
func (m *MockSecretCommands) ListLocal(ctx context.Context) ([]models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLocal", ctx)
	ret0, _ := ret[0].([]models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLocal indicates an expected call of ListLocal.
func (mr *MockSecretCommandsMockRecorder) ListLocal(ctx any) *MockSecretCommandsListLocalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLocal", reflect.TypeOf((*MockSecretCommands)(nil).ListLocal), ctx)
	return &MockSecretCommandsListLocalCall{Call: call}
}

// MockSecretCommandsListLocalCall wrap *gomock.Call
type MockSecretCommandsListLocalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsListLocalCall) Return(arg0 []models.Entry, arg1 error) *MockSecretCommandsListLocalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsListLocalCall) Do(f func(context.Context) ([]models.Entry, error)) *MockSecretCommandsListLocalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsListLocalCall) DoAndReturn(f func(context.Context) ([]models.Entry, error)) *MockSecretCommandsListLocalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetCard mocks base method.
func (m *MockSecretCommands) SetCard(ctx context.Context, meta usecase.EntryMetadata, card models.CardPayload, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCard", ctx, meta, card, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCard indicates an expected call of SetCard.
func (mr *MockSecretCommandsMockRecorder) SetCard(ctx, meta, card, masterPass any) *MockSecretCommandsSetCardCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCard", reflect.TypeOf((*MockSecretCommands)(nil).SetCard), ctx, meta, card, masterPass)
	return &MockSecretCommandsSetCardCall{Call: call}
}

// MockSecretCommandsSetCardCall wrap *gomock.Call
type MockSecretCommandsSetCardCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsSetCardCall) Return(arg0 error) *MockSecretCommandsSetCardCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsSetCardCall) Do(f func(context.Context, usecase.EntryMetadata, models.CardPayload, string) error) *MockSecretCommandsSetCardCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsSetCardCall) DoAndReturn(f func(context.Context, usecase.EntryMetadata, models.CardPayload, string) error) *MockSecretCommandsSetCardCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetFile mocks base method.
func (m *MockSecretCommands) SetFile(ctx context.Context, meta usecase.EntryMetadata, originalFilename string, data []byte, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFile", ctx, meta, originalFilename, data, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFile indicates an expected call of SetFile.
func (mr *MockSecretCommandsMockRecorder) SetFile(ctx, meta, originalFilename, data, masterPass any) *MockSecretCommandsSetFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFile", reflect.TypeOf((*MockSecretCommands)(nil).SetFile), ctx, meta, originalFilename, data, masterPass)
	return &MockSecretCommandsSetFileCall{Call: call}
}

// MockSecretCommandsSetFileCall wrap *gomock.Call
type MockSecretCommandsSetFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsSetFileCall) Return(arg0 error) *MockSecretCommandsSetFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsSetFileCall) Do(f func(context.Context, usecase.EntryMetadata, string, []byte, string) error) *MockSecretCommandsSetFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsSetFileCall) DoAndReturn(f func(context.Context, usecase.EntryMetadata, string, []byte, string) error) *MockSecretCommandsSetFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetPassword mocks base method.
func (m *MockSecretCommands) SetPassword(ctx context.Context, meta usecase.EntryMetadata, password, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPassword", ctx, meta, password, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPassword indicates an expected call of SetPassword.
func (mr *MockSecretCommandsMockRecorder) SetPassword(ctx, meta, password, masterPass any) *MockSecretCommandsSetPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPassword", reflect.TypeOf((*MockSecretCommands)(nil).SetPassword), ctx, meta, password, masterPass)
	return &MockSecretCommandsSetPasswordCall{Call: call}
}

// MockSecretCommandsSetPasswordCall wrap *gomock.Call
type MockSecretCommandsSetPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsSetPasswordCall) Return(arg0 error) *MockSecretCommandsSetPasswordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsSetPasswordCall) Do(f func(context.Context, usecase.EntryMetadata, string, string) error) *MockSecretCommandsSetPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsSetPasswordCall) DoAndReturn(f func(context.Context, usecase.EntryMetadata, string, string) error) *MockSecretCommandsSetPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetText mocks base method.
func (m *MockSecretCommands) SetText(ctx context.Context, meta usecase.EntryMetadata, text, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetText", ctx, meta, text, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetText indicates an expected call of SetText.
func (mr *MockSecretCommandsMockRecorder) SetText(ctx, meta, text, masterPass any) *MockSecretCommandsSetTextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetText", reflect.TypeOf((*MockSecretCommands)(nil).SetText), ctx, meta, text, masterPass)
	return &MockSecretCommandsSetTextCall{Call: call}
}

// MockSecretCommandsSetTextCall wrap *gomock.Call
type MockSecretCommandsSetTextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsSetTextCall) Return(arg0 error) *MockSecretCommandsSetTextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsSetTextCall) Do(f func(context.Context, usecase.EntryMetadata, string, string) error) *MockSecretCommandsSetTextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsSetTextCall) DoAndReturn(f func(context.Context, usecase.EntryMetadata, string, string) error) *MockSecretCommandsSetTextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCard mocks base method.
func (m *MockSecretCommands) UpdateCard(ctx context.Context, id uuid.UUID, meta usecase.EntryMetadata, card models.CardPayload, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCard", ctx, id, meta, card, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCard indicates an expected call of UpdateCard.
func (mr *MockSecretCommandsMockRecorder) UpdateCard(ctx, id, meta, card, masterPass any) *MockSecretCommandsUpdateCardCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCard", reflect.TypeOf((*MockSecretCommands)(nil).UpdateCard), ctx, id, meta, card, masterPass)
	return &MockSecretCommandsUpdateCardCall{Call: call}
}

// MockSecretCommandsUpdateCardCall wrap *gomock.Call
type MockSecretCommandsUpdateCardCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsUpdateCardCall) Return(arg0 error) *MockSecretCommandsUpdateCardCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsUpdateCardCall) Do(f func(context.Context, uuid.UUID, usecase.EntryMetadata, models.CardPayload, string) error) *MockSecretCommandsUpdateCardCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsUpdateCardCall) DoAndReturn(f func(context.Context, uuid.UUID, usecase.EntryMetadata, models.CardPayload, string) error) *MockSecretCommandsUpdateCardCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateFile mocks base method.
func (m *MockSecretCommands) UpdateFile(ctx context.Context, id uuid.UUID, meta usecase.EntryMetadata, masterPass string, replacePayload bool, newFile []byte, newOrigName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", ctx, id, meta, masterPass, replacePayload, newFile, newOrigName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFile indicates an expected call of UpdateFile.
func (mr *MockSecretCommandsMockRecorder) UpdateFile(ctx, id, meta, masterPass, replacePayload, newFile, newOrigName any) *MockSecretCommandsUpdateFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockSecretCommands)(nil).UpdateFile), ctx, id, meta, masterPass, replacePayload, newFile, newOrigName)
	return &MockSecretCommandsUpdateFileCall{Call: call}
}

// MockSecretCommandsUpdateFileCall wrap *gomock.Call
type MockSecretCommandsUpdateFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsUpdateFileCall) Return(arg0 error) *MockSecretCommandsUpdateFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsUpdateFileCall) Do(f func(context.Context, uuid.UUID, usecase.EntryMetadata, string, bool, []byte, string) error) *MockSecretCommandsUpdateFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsUpdateFileCall) DoAndReturn(f func(context.Context, uuid.UUID, usecase.EntryMetadata, string, bool, []byte, string) error) *MockSecretCommandsUpdateFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdatePassword mocks base method.
func (m *MockSecretCommands) UpdatePassword(ctx context.Context, id uuid.UUID, meta usecase.EntryMetadata, password, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, id, meta, password, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockSecretCommandsMockRecorder) UpdatePassword(ctx, id, meta, password, masterPass any) *MockSecretCommandsUpdatePasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockSecretCommands)(nil).UpdatePassword), ctx, id, meta, password, masterPass)
	return &MockSecretCommandsUpdatePasswordCall{Call: call}
}

// MockSecretCommandsUpdatePasswordCall wrap *gomock.Call
type MockSecretCommandsUpdatePasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsUpdatePasswordCall) Return(arg0 error) *MockSecretCommandsUpdatePasswordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsUpdatePasswordCall) Do(f func(context.Context, uuid.UUID, usecase.EntryMetadata, string, string) error) *MockSecretCommandsUpdatePasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsUpdatePasswordCall) DoAndReturn(f func(context.Context, uuid.UUID, usecase.EntryMetadata, string, string) error) *MockSecretCommandsUpdatePasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateText mocks base method.
func (m *MockSecretCommands) UpdateText(ctx context.Context, id uuid.UUID, meta usecase.EntryMetadata, text, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateText", ctx, id, meta, text, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateText indicates an expected call of UpdateText.
func (mr *MockSecretCommandsMockRecorder) UpdateText(ctx, id, meta, text, masterPass any) *MockSecretCommandsUpdateTextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateText", reflect.TypeOf((*MockSecretCommands)(nil).UpdateText), ctx, id, meta, text, masterPass)
	return &MockSecretCommandsUpdateTextCall{Call: call}
}

// MockSecretCommandsUpdateTextCall wrap *gomock.Call
type MockSecretCommandsUpdateTextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretCommandsUpdateTextCall) Return(arg0 error) *MockSecretCommandsUpdateTextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretCommandsUpdateTextCall) Do(f func(context.Context, uuid.UUID, usecase.EntryMetadata, string, string) error) *MockSecretCommandsUpdateTextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretCommandsUpdateTextCall) DoAndReturn(f func(context.Context, uuid.UUID, usecase.EntryMetadata, string, string) error) *MockSecretCommandsUpdateTextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSyncCommands is a mock of SyncCommands interface.
type MockSyncCommands struct {
	ctrl     *gomock.Controller
	recorder *MockSyncCommandsMockRecorder
	isgomock struct{}
}

// MockSyncCommandsMockRecorder is the mock recorder for MockSyncCommands.
type MockSyncCommandsMockRecorder struct {
	mock *MockSyncCommands
}

// NewMockSyncCommands creates a new mock instance.
func NewMockSyncCommands(ctrl *gomock.Controller) *MockSyncCommands {
	mock := &MockSyncCommands{ctrl: ctrl}
	mock.recorder = &MockSyncCommandsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncCommands) EXPECT() *MockSyncCommandsMockRecorder {
	return m.recorder
}

// Sync mocks base method.
func (m *MockSyncCommands) Sync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockSyncCommandsMockRecorder) Sync(ctx any) *MockSyncCommandsSyncCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockSyncCommands)(nil).Sync), ctx)
	return &MockSyncCommandsSyncCall{Call: call}
}

// MockSyncCommandsSyncCall wrap *gomock.Call
type MockSyncCommandsSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncCommandsSyncCall) Return(arg0 error) *MockSyncCommandsSyncCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncCommandsSyncCall) Do(f func(context.Context) error) *MockSyncCommandsSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncCommandsSyncCall) DoAndReturn(f func(context.Context) error) *MockSyncCommandsSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
