erDiagram
    ENTRY {
        int id PK
        int user_id "user id in auther service"
        string dek "data encryption key"
        string type "account|text|binary|bank_card"
        text payload "aes encrypted with master key json data"
        text meta "custom jsonb meta, not encrypted"
        bool is_deleted
        timestamp created_at
        timestamp updated_at
        int version
    }