// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_usecase_test.go -package=delivery -source=delivery.go UseCase
//

// Package delivery is a generated GoMock package.
package delivery

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	models "github.com/georgg2003/skeeper/internal/skeeper/pkg/models"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Sync mocks base method.
func (m *MockUseCase) Sync(arg0 context.Context, arg1 models.SyncRequest) (models.SyncResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", arg0, arg1)
	ret0, _ := ret[0].(models.SyncResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockUseCaseMockRecorder) Sync(arg0, arg1 any) *MockUseCaseSyncCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockUseCase)(nil).Sync), arg0, arg1)
	return &MockUseCaseSyncCall{Call: call}
}

// MockUseCaseSyncCall wrap *gomock.Call
type MockUseCaseSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUseCaseSyncCall) Return(arg0 models.SyncResponse, arg1 error) *MockUseCaseSyncCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUseCaseSyncCall) Do(f func(context.Context, models.SyncRequest) (models.SyncResponse, error)) *MockUseCaseSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUseCaseSyncCall) DoAndReturn(f func(context.Context, models.SyncRequest) (models.SyncResponse, error)) *MockUseCaseSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
