// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go
//
// Generated by this command:
//
//	mockgen -typed -destination=mock_usecase_test.go -package=delivery -source=delivery.go UseCase
//

// Package delivery is a generated GoMock package.
package delivery

import (
	context "context"
	reflect "reflect"

	models "github.com/georgg2003/skeeper/internal/skeeper/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetVaultCrypto mocks base method.
func (m *MockUseCase) GetVaultCrypto(arg0 context.Context) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVaultCrypto", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVaultCrypto indicates an expected call of GetVaultCrypto.
func (mr *MockUseCaseMockRecorder) GetVaultCrypto(arg0 any) *MockUseCaseGetVaultCryptoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVaultCrypto", reflect.TypeOf((*MockUseCase)(nil).GetVaultCrypto), arg0)
	return &MockUseCaseGetVaultCryptoCall{Call: call}
}

// MockUseCaseGetVaultCryptoCall wrap *gomock.Call
type MockUseCaseGetVaultCryptoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUseCaseGetVaultCryptoCall) Return(arg0, arg1 []byte, arg2 error) *MockUseCaseGetVaultCryptoCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUseCaseGetVaultCryptoCall) Do(f func(context.Context) ([]byte, []byte, error)) *MockUseCaseGetVaultCryptoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUseCaseGetVaultCryptoCall) DoAndReturn(f func(context.Context) ([]byte, []byte, error)) *MockUseCaseGetVaultCryptoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutVaultCrypto mocks base method.
func (m *MockUseCase) PutVaultCrypto(arg0 context.Context, arg1, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutVaultCrypto", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutVaultCrypto indicates an expected call of PutVaultCrypto.
func (mr *MockUseCaseMockRecorder) PutVaultCrypto(arg0, arg1, arg2 any) *MockUseCasePutVaultCryptoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutVaultCrypto", reflect.TypeOf((*MockUseCase)(nil).PutVaultCrypto), arg0, arg1, arg2)
	return &MockUseCasePutVaultCryptoCall{Call: call}
}

// MockUseCasePutVaultCryptoCall wrap *gomock.Call
type MockUseCasePutVaultCryptoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUseCasePutVaultCryptoCall) Return(arg0 error) *MockUseCasePutVaultCryptoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUseCasePutVaultCryptoCall) Do(f func(context.Context, []byte, []byte) error) *MockUseCasePutVaultCryptoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUseCasePutVaultCryptoCall) DoAndReturn(f func(context.Context, []byte, []byte) error) *MockUseCasePutVaultCryptoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Sync mocks base method.
func (m *MockUseCase) Sync(arg0 context.Context, arg1 models.SyncRequest) (models.SyncResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", arg0, arg1)
	ret0, _ := ret[0].(models.SyncResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockUseCaseMockRecorder) Sync(arg0, arg1 any) *MockUseCaseSyncCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockUseCase)(nil).Sync), arg0, arg1)
	return &MockUseCaseSyncCall{Call: call}
}

// MockUseCaseSyncCall wrap *gomock.Call
type MockUseCaseSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUseCaseSyncCall) Return(arg0 models.SyncResponse, arg1 error) *MockUseCaseSyncCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUseCaseSyncCall) Do(f func(context.Context, models.SyncRequest) (models.SyncResponse, error)) *MockUseCaseSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUseCaseSyncCall) DoAndReturn(f func(context.Context, models.SyncRequest) (models.SyncResponse, error)) *MockUseCaseSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
