// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/auther.proto

package api

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Email       *string                `protobuf:"bytes,2,opt,name=email"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_auther_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_auther_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *User) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *User) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *User) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *User) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *User) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *User) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Email = nil
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    *int64
	Email *string
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Email = b.Email
	}
	return m0
}

type CreateUserRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email       *string                `protobuf:"bytes,1,opt,name=email"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_auther_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auther_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *CreateUserRequest) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateUserRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CreateUserRequest) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateUserRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateUserRequest) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Email = nil
}

func (x *CreateUserRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type CreateUserRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email    *string
	Password *string
}

func (b0 CreateUserRequest_builder) Build() *CreateUserRequest {
	m0 := &CreateUserRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Email = b.Email
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type CreateUserResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *User                  `protobuf:"bytes,1,opt,name=user"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_api_auther_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auther_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *CreateUserResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *CreateUserResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *CreateUserResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type CreateUserResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *User
}

func (b0 CreateUserResponse_builder) Build() *CreateUserResponse {
	m0 := &CreateUserResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

type LoginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email       *string                `protobuf:"bytes,1,opt,name=email"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_auther_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auther_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginRequest) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginRequest) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Email = nil
}

func (x *LoginRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email    *string
	Password *string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Email = b.Email
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type Token struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_api_auther_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_api_auther_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Token) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *Token) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *Token) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Token) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *Token) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Token) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *Token) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *Token) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

type Token_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token     *string
	ExpiresAt *timestamppb.Timestamp
}

func (b0 Token_builder) Build() *Token {
	m0 := &Token{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Token = b.Token
	}
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	return m0
}

type LoginResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefreshToken *Token                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken"`
	xxx_hidden_AccessToken  *Token                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken"`
	xxx_hidden_User         *User                  `protobuf:"bytes,3,opt,name=user"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_auther_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auther_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetRefreshToken() *Token {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return nil
}

func (x *LoginResponse) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *LoginResponse) SetRefreshToken(v *Token) {
	x.xxx_hidden_RefreshToken = v
}

func (x *LoginResponse) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *LoginResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *LoginResponse) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RefreshToken != nil
}

func (x *LoginResponse) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *LoginResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *LoginResponse) ClearRefreshToken() {
	x.xxx_hidden_RefreshToken = nil
}

func (x *LoginResponse) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

func (x *LoginResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefreshToken *Token
	AccessToken  *Token
	User         *User
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefreshToken = b.RefreshToken
	x.xxx_hidden_AccessToken = b.AccessToken
	x.xxx_hidden_User = b.User
	return m0
}

type ExchangeTokenRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ExchangeTokenRequest) Reset() {
	*x = ExchangeTokenRequest{}
	mi := &file_api_auther_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTokenRequest) ProtoMessage() {}

func (x *ExchangeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auther_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExchangeTokenRequest) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *ExchangeTokenRequest) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ExchangeTokenRequest) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ExchangeTokenRequest) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RefreshToken = nil
}

type ExchangeTokenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefreshToken *string
}

func (b0 ExchangeTokenRequest_builder) Build() *ExchangeTokenRequest {
	m0 := &ExchangeTokenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	return m0
}

type ExchangeTokenResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefreshToken *Token                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken"`
	xxx_hidden_AccessToken  *Token                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ExchangeTokenResponse) Reset() {
	*x = ExchangeTokenResponse{}
	mi := &file_api_auther_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTokenResponse) ProtoMessage() {}

func (x *ExchangeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auther_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExchangeTokenResponse) GetRefreshToken() *Token {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return nil
}

func (x *ExchangeTokenResponse) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *ExchangeTokenResponse) SetRefreshToken(v *Token) {
	x.xxx_hidden_RefreshToken = v
}

func (x *ExchangeTokenResponse) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *ExchangeTokenResponse) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RefreshToken != nil
}

func (x *ExchangeTokenResponse) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *ExchangeTokenResponse) ClearRefreshToken() {
	x.xxx_hidden_RefreshToken = nil
}

func (x *ExchangeTokenResponse) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type ExchangeTokenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefreshToken *Token
	AccessToken  *Token
}

func (b0 ExchangeTokenResponse_builder) Build() *ExchangeTokenResponse {
	m0 := &ExchangeTokenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefreshToken = b.RefreshToken
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

var File_api_auther_proto protoreflect.FileDescriptor

const file_api_auther_proto_rawDesc = "" +
	"\n" +
	"\x10api/auther.proto\x12\x06auther\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"E\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"6\n" +
	"\x12CreateUserResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.auther.UserR\x04user\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"X\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x97\x01\n" +
	"\rLoginResponse\x122\n" +
	"\rrefresh_token\x18\x01 \x01(\v2\r.auther.TokenR\frefreshToken\x120\n" +
	"\faccess_token\x18\x02 \x01(\v2\r.auther.TokenR\vaccessToken\x12 \n" +
	"\x04user\x18\x03 \x01(\v2\f.auther.UserR\x04user\";\n" +
	"\x14ExchangeTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"}\n" +
	"\x15ExchangeTokenResponse\x122\n" +
	"\rrefresh_token\x18\x01 \x01(\v2\r.auther.TokenR\frefreshToken\x120\n" +
	"\faccess_token\x18\x02 \x01(\v2\r.auther.TokenR\vaccessToken2\xd1\x01\n" +
	"\x06Auther\x12C\n" +
	"\n" +
	"CreateUser\x12\x19.auther.CreateUserRequest\x1a\x1a.auther.CreateUserResponse\x124\n" +
	"\x05Login\x12\x14.auther.LoginRequest\x1a\x15.auther.LoginResponse\x12L\n" +
	"\rExchangeToken\x12\x1c.auther.ExchangeTokenRequest\x1a\x1d.auther.ExchangeTokenResponseB*Z(github.com/georgg2003/skeeper/auther/apib\beditionsp\xe8\a"

var file_api_auther_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_auther_proto_goTypes = []any{
	(*User)(nil),                  // 0: auther.User
	(*CreateUserRequest)(nil),     // 1: auther.CreateUserRequest
	(*CreateUserResponse)(nil),    // 2: auther.CreateUserResponse
	(*LoginRequest)(nil),          // 3: auther.LoginRequest
	(*Token)(nil),                 // 4: auther.Token
	(*LoginResponse)(nil),         // 5: auther.LoginResponse
	(*ExchangeTokenRequest)(nil),  // 6: auther.ExchangeTokenRequest
	(*ExchangeTokenResponse)(nil), // 7: auther.ExchangeTokenResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_api_auther_proto_depIdxs = []int32{
	0,  // 0: auther.CreateUserResponse.user:type_name -> auther.User
	8,  // 1: auther.Token.expires_at:type_name -> google.protobuf.Timestamp
	4,  // 2: auther.LoginResponse.refresh_token:type_name -> auther.Token
	4,  // 3: auther.LoginResponse.access_token:type_name -> auther.Token
	0,  // 4: auther.LoginResponse.user:type_name -> auther.User
	4,  // 5: auther.ExchangeTokenResponse.refresh_token:type_name -> auther.Token
	4,  // 6: auther.ExchangeTokenResponse.access_token:type_name -> auther.Token
	1,  // 7: auther.Auther.CreateUser:input_type -> auther.CreateUserRequest
	3,  // 8: auther.Auther.Login:input_type -> auther.LoginRequest
	6,  // 9: auther.Auther.ExchangeToken:input_type -> auther.ExchangeTokenRequest
	2,  // 10: auther.Auther.CreateUser:output_type -> auther.CreateUserResponse
	5,  // 11: auther.Auther.Login:output_type -> auther.LoginResponse
	7,  // 12: auther.Auther.ExchangeToken:output_type -> auther.ExchangeTokenResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_auther_proto_init() }
func file_api_auther_proto_init() {
	if File_api_auther_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auther_proto_rawDesc), len(file_api_auther_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auther_proto_goTypes,
		DependencyIndexes: file_api_auther_proto_depIdxs,
		MessageInfos:      file_api_auther_proto_msgTypes,
	}.Build()
	File_api_auther_proto = out.File
	file_api_auther_proto_goTypes = nil
	file_api_auther_proto_depIdxs = nil
}
