// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/skeeper.proto

package api

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uuid         string                 `protobuf:"bytes,1,opt,name=uuid,proto3"`
	xxx_hidden_Type         string                 `protobuf:"bytes,2,opt,name=type,proto3"`
	xxx_hidden_EncryptedDek []byte                 `protobuf:"bytes,3,opt,name=encrypted_dek,json=encryptedDek,proto3"`
	xxx_hidden_Payload      []byte                 `protobuf:"bytes,4,opt,name=payload,proto3"`
	xxx_hidden_Meta         []byte                 `protobuf:"bytes,5,opt,name=meta,proto3"`
	xxx_hidden_Version      int64                  `protobuf:"varint,6,opt,name=version,proto3"`
	xxx_hidden_IsDeleted    bool                   `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3"`
	xxx_hidden_UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_api_skeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_api_skeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Entry) GetUuid() string {
	if x != nil {
		return x.xxx_hidden_Uuid
	}
	return ""
}

func (x *Entry) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *Entry) GetEncryptedDek() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedDek
	}
	return nil
}

func (x *Entry) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *Entry) GetMeta() []byte {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *Entry) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Entry) GetIsDeleted() bool {
	if x != nil {
		return x.xxx_hidden_IsDeleted
	}
	return false
}

func (x *Entry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Entry) SetUuid(v string) {
	x.xxx_hidden_Uuid = v
}

func (x *Entry) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *Entry) SetEncryptedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedDek = v
}

func (x *Entry) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
}

func (x *Entry) SetMeta(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Meta = v
}

func (x *Entry) SetVersion(v int64) {
	x.xxx_hidden_Version = v
}

func (x *Entry) SetIsDeleted(v bool) {
	x.xxx_hidden_IsDeleted = v
}

func (x *Entry) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Entry) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Entry) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uuid         string
	Type         string
	EncryptedDek []byte
	Payload      []byte
	Meta         []byte
	Version      int64
	IsDeleted    bool
	UpdatedAt    *timestamppb.Timestamp
}

func (b0 Entry_builder) Build() *Entry {
	m0 := &Entry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Uuid = b.Uuid
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_EncryptedDek = b.EncryptedDek
	x.xxx_hidden_Payload = b.Payload
	x.xxx_hidden_Meta = b.Meta
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_IsDeleted = b.IsDeleted
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type SyncRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Updates    *[]*Entry              `protobuf:"bytes,1,rep,name=updates,proto3"`
	xxx_hidden_LastSyncAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_sync_at,json=lastSyncAt,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_skeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_skeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncRequest) GetUpdates() []*Entry {
	if x != nil {
		if x.xxx_hidden_Updates != nil {
			return *x.xxx_hidden_Updates
		}
	}
	return nil
}

func (x *SyncRequest) GetLastSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastSyncAt
	}
	return nil
}

func (x *SyncRequest) SetUpdates(v []*Entry) {
	x.xxx_hidden_Updates = &v
}

func (x *SyncRequest) SetLastSyncAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastSyncAt = v
}

func (x *SyncRequest) HasLastSyncAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastSyncAt != nil
}

func (x *SyncRequest) ClearLastSyncAt() {
	x.xxx_hidden_LastSyncAt = nil
}

type SyncRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Updates    []*Entry
	LastSyncAt *timestamppb.Timestamp
}

func (b0 SyncRequest_builder) Build() *SyncRequest {
	m0 := &SyncRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Updates = &b.Updates
	x.xxx_hidden_LastSyncAt = b.LastSyncAt
	return m0
}

type SyncResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Updates       *[]*Entry              `protobuf:"bytes,1,rep,name=updates,proto3"`
	xxx_hidden_CurrentSyncAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=current_sync_at,json=currentSyncAt,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_skeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_skeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncResponse) GetUpdates() []*Entry {
	if x != nil {
		if x.xxx_hidden_Updates != nil {
			return *x.xxx_hidden_Updates
		}
	}
	return nil
}

func (x *SyncResponse) GetCurrentSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CurrentSyncAt
	}
	return nil
}

func (x *SyncResponse) SetUpdates(v []*Entry) {
	x.xxx_hidden_Updates = &v
}

func (x *SyncResponse) SetCurrentSyncAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CurrentSyncAt = v
}

func (x *SyncResponse) HasCurrentSyncAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CurrentSyncAt != nil
}

func (x *SyncResponse) ClearCurrentSyncAt() {
	x.xxx_hidden_CurrentSyncAt = nil
}

type SyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Updates       []*Entry
	CurrentSyncAt *timestamppb.Timestamp
}

func (b0 SyncResponse_builder) Build() *SyncResponse {
	m0 := &SyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Updates = &b.Updates
	x.xxx_hidden_CurrentSyncAt = b.CurrentSyncAt
	return m0
}

type FileMetadata struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EntryId  string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3"`
	xxx_hidden_Filename string                 `protobuf:"bytes,2,opt,name=filename,proto3"`
	xxx_hidden_Size     int64                  `protobuf:"varint,3,opt,name=size,proto3"`
	xxx_hidden_Checksum string                 `protobuf:"bytes,4,opt,name=checksum,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_api_skeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_skeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileMetadata) GetEntryId() string {
	if x != nil {
		return x.xxx_hidden_EntryId
	}
	return ""
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.xxx_hidden_Filename
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *FileMetadata) GetChecksum() string {
	if x != nil {
		return x.xxx_hidden_Checksum
	}
	return ""
}

func (x *FileMetadata) SetEntryId(v string) {
	x.xxx_hidden_EntryId = v
}

func (x *FileMetadata) SetFilename(v string) {
	x.xxx_hidden_Filename = v
}

func (x *FileMetadata) SetSize(v int64) {
	x.xxx_hidden_Size = v
}

func (x *FileMetadata) SetChecksum(v string) {
	x.xxx_hidden_Checksum = v
}

type FileMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EntryId  string
	Filename string
	Size     int64
	Checksum string
}

func (b0 FileMetadata_builder) Build() *FileMetadata {
	m0 := &FileMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EntryId = b.EntryId
	x.xxx_hidden_Filename = b.Filename
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_Checksum = b.Checksum
	return m0
}

type UploadFileRequest struct {
	state           protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Data isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_api_skeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_skeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadFileRequest) GetInfo() *FileMetadata {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*uploadFileRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*uploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *UploadFileRequest) SetInfo(v *FileMetadata) {
	if v == nil {
		x.xxx_hidden_Data = nil
		return
	}
	x.xxx_hidden_Data = &uploadFileRequest_Info{v}
}

func (x *UploadFileRequest) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = &uploadFileRequest_Chunk{v}
}

func (x *UploadFileRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *UploadFileRequest) HasInfo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*uploadFileRequest_Info)
	return ok
}

func (x *UploadFileRequest) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*uploadFileRequest_Chunk)
	return ok
}

func (x *UploadFileRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *UploadFileRequest) ClearInfo() {
	if _, ok := x.xxx_hidden_Data.(*uploadFileRequest_Info); ok {
		x.xxx_hidden_Data = nil
	}
}

func (x *UploadFileRequest) ClearChunk() {
	if _, ok := x.xxx_hidden_Data.(*uploadFileRequest_Chunk); ok {
		x.xxx_hidden_Data = nil
	}
}

const UploadFileRequest_Data_not_set_case case_UploadFileRequest_Data = 0
const UploadFileRequest_Info_case case_UploadFileRequest_Data = 1
const UploadFileRequest_Chunk_case case_UploadFileRequest_Data = 2

func (x *UploadFileRequest) WhichData() case_UploadFileRequest_Data {
	if x == nil {
		return UploadFileRequest_Data_not_set_case
	}
	switch x.xxx_hidden_Data.(type) {
	case *uploadFileRequest_Info:
		return UploadFileRequest_Info_case
	case *uploadFileRequest_Chunk:
		return UploadFileRequest_Chunk_case
	default:
		return UploadFileRequest_Data_not_set_case
	}
}

type UploadFileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Data:
	Info  *FileMetadata
	Chunk []byte
	// -- end of xxx_hidden_Data
}

func (b0 UploadFileRequest_builder) Build() *UploadFileRequest {
	m0 := &UploadFileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Info != nil {
		x.xxx_hidden_Data = &uploadFileRequest_Info{b.Info}
	}
	if b.Chunk != nil {
		x.xxx_hidden_Data = &uploadFileRequest_Chunk{b.Chunk}
	}
	return m0
}

type case_UploadFileRequest_Data protoreflect.FieldNumber

func (x case_UploadFileRequest_Data) String() string {
	md := file_api_skeeper_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type uploadFileRequest_Info struct {
	Info *FileMetadata `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type uploadFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*uploadFileRequest_Info) isUploadFileRequest_Data() {}

func (*uploadFileRequest_Chunk) isUploadFileRequest_Data() {}

type DownloadFileRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EntryId string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_api_skeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_skeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadFileRequest) GetEntryId() string {
	if x != nil {
		return x.xxx_hidden_EntryId
	}
	return ""
}

func (x *DownloadFileRequest) SetEntryId(v string) {
	x.xxx_hidden_EntryId = v
}

type DownloadFileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EntryId string
}

func (b0 DownloadFileRequest_builder) Build() *DownloadFileRequest {
	m0 := &DownloadFileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EntryId = b.EntryId
	return m0
}

type FileChunk struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Chunk []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_api_skeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_skeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileChunk) GetChunk() []byte {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return nil
}

func (x *FileChunk) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Chunk = v
}

type FileChunk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Chunk []byte
}

func (b0 FileChunk_builder) Build() *FileChunk {
	m0 := &FileChunk{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Chunk = b.Chunk
	return m0
}

var File_api_skeeper_proto protoreflect.FileDescriptor

const file_api_skeeper_proto_rawDesc = "" +
	"\n" +
	"\x11api/skeeper.proto\x12\askeeper\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n" +
	"\x05Entry\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rencrypted_dek\x18\x03 \x01(\fR\fencryptedDek\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x12\n" +
	"\x04meta\x18\x05 \x01(\fR\x04meta\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bR\tisDeleted\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"u\n" +
	"\vSyncRequest\x12(\n" +
	"\aupdates\x18\x01 \x03(\v2\x0e.skeeper.EntryR\aupdates\x12<\n" +
	"\flast_sync_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSyncAt\"|\n" +
	"\fSyncResponse\x12(\n" +
	"\aupdates\x18\x01 \x03(\v2\x0e.skeeper.EntryR\aupdates\x12B\n" +
	"\x0fcurrent_sync_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rcurrentSyncAt\"u\n" +
	"\fFileMetadata\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"`\n" +
	"\x11UploadFileRequest\x12+\n" +
	"\x04info\x18\x01 \x01(\v2\x15.skeeper.FileMetadataH\x00R\x04info\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"0\n" +
	"\x13DownloadFileRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\"!\n" +
	"\tFileChunk\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2>\n" +
	"\aSkeeper\x123\n" +
	"\x04Sync\x12\x14.skeeper.SyncRequest\x1a\x15.skeeper.SyncResponseB#Z!github.com/georgg2003/skeeper/apib\x06proto3"

var file_api_skeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_skeeper_proto_goTypes = []any{
	(*Entry)(nil),                 // 0: skeeper.Entry
	(*SyncRequest)(nil),           // 1: skeeper.SyncRequest
	(*SyncResponse)(nil),          // 2: skeeper.SyncResponse
	(*FileMetadata)(nil),          // 3: skeeper.FileMetadata
	(*UploadFileRequest)(nil),     // 4: skeeper.UploadFileRequest
	(*DownloadFileRequest)(nil),   // 5: skeeper.DownloadFileRequest
	(*FileChunk)(nil),             // 6: skeeper.FileChunk
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_api_skeeper_proto_depIdxs = []int32{
	7, // 0: skeeper.Entry.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: skeeper.SyncRequest.updates:type_name -> skeeper.Entry
	7, // 2: skeeper.SyncRequest.last_sync_at:type_name -> google.protobuf.Timestamp
	0, // 3: skeeper.SyncResponse.updates:type_name -> skeeper.Entry
	7, // 4: skeeper.SyncResponse.current_sync_at:type_name -> google.protobuf.Timestamp
	3, // 5: skeeper.UploadFileRequest.info:type_name -> skeeper.FileMetadata
	1, // 6: skeeper.Skeeper.Sync:input_type -> skeeper.SyncRequest
	2, // 7: skeeper.Skeeper.Sync:output_type -> skeeper.SyncResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_skeeper_proto_init() }
func file_api_skeeper_proto_init() {
	if File_api_skeeper_proto != nil {
		return
	}
	file_api_skeeper_proto_msgTypes[4].OneofWrappers = []any{
		(*uploadFileRequest_Info)(nil),
		(*uploadFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_skeeper_proto_rawDesc), len(file_api_skeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_skeeper_proto_goTypes,
		DependencyIndexes: file_api_skeeper_proto_depIdxs,
		MessageInfos:      file_api_skeeper_proto_msgTypes,
	}.Build()
	File_api_skeeper_proto = out.File
	file_api_skeeper_proto_goTypes = nil
	file_api_skeeper_proto_depIdxs = nil
}
