// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/skeeper.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkeeperService_ListEntries_FullMethodName = "/skeeper.SkeeperService/ListEntries"
	SkeeperService_GetEntries_FullMethodName  = "/skeeper.SkeeperService/GetEntries"
	SkeeperService_UploadFile_FullMethodName  = "/skeeper.SkeeperService/UploadFile"
	SkeeperService_GetFile_FullMethodName     = "/skeeper.SkeeperService/GetFile"
	SkeeperService_SyncEntries_FullMethodName = "/skeeper.SkeeperService/SyncEntries"
)

// SkeeperServiceClient is the client API for SkeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkeeperServiceClient interface {
	ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListEntriesResponse], error)
	GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetEntriesResponse], error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileRequest, UploadFileResponse], error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetFileResponse], error)
	SyncEntries(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SyncEntriesRequest, SyncEntriesResponse], error)
}

type skeeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkeeperServiceClient(cc grpc.ClientConnInterface) SkeeperServiceClient {
	return &skeeperServiceClient{cc}
}

func (c *skeeperServiceClient) ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListEntriesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SkeeperService_ServiceDesc.Streams[0], SkeeperService_ListEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListEntriesRequest, ListEntriesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_ListEntriesClient = grpc.ServerStreamingClient[ListEntriesResponse]

func (c *skeeperServiceClient) GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetEntriesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SkeeperService_ServiceDesc.Streams[1], SkeeperService_GetEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetEntriesRequest, GetEntriesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_GetEntriesClient = grpc.ServerStreamingClient[GetEntriesResponse]

func (c *skeeperServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileRequest, UploadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SkeeperService_ServiceDesc.Streams[2], SkeeperService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFileRequest, UploadFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_UploadFileClient = grpc.ClientStreamingClient[UploadFileRequest, UploadFileResponse]

func (c *skeeperServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SkeeperService_ServiceDesc.Streams[3], SkeeperService_GetFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetFileRequest, GetFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_GetFileClient = grpc.ServerStreamingClient[GetFileResponse]

func (c *skeeperServiceClient) SyncEntries(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SyncEntriesRequest, SyncEntriesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SkeeperService_ServiceDesc.Streams[4], SkeeperService_SyncEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncEntriesRequest, SyncEntriesResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_SyncEntriesClient = grpc.BidiStreamingClient[SyncEntriesRequest, SyncEntriesResponse]

// SkeeperServiceServer is the server API for SkeeperService service.
// All implementations must embed UnimplementedSkeeperServiceServer
// for forward compatibility.
type SkeeperServiceServer interface {
	ListEntries(*ListEntriesRequest, grpc.ServerStreamingServer[ListEntriesResponse]) error
	GetEntries(*GetEntriesRequest, grpc.ServerStreamingServer[GetEntriesResponse]) error
	UploadFile(grpc.ClientStreamingServer[UploadFileRequest, UploadFileResponse]) error
	GetFile(*GetFileRequest, grpc.ServerStreamingServer[GetFileResponse]) error
	SyncEntries(grpc.BidiStreamingServer[SyncEntriesRequest, SyncEntriesResponse]) error
	mustEmbedUnimplementedSkeeperServiceServer()
}

// UnimplementedSkeeperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkeeperServiceServer struct{}

func (UnimplementedSkeeperServiceServer) ListEntries(*ListEntriesRequest, grpc.ServerStreamingServer[ListEntriesResponse]) error {
	return status.Error(codes.Unimplemented, "method ListEntries not implemented")
}
func (UnimplementedSkeeperServiceServer) GetEntries(*GetEntriesRequest, grpc.ServerStreamingServer[GetEntriesResponse]) error {
	return status.Error(codes.Unimplemented, "method GetEntries not implemented")
}
func (UnimplementedSkeeperServiceServer) UploadFile(grpc.ClientStreamingServer[UploadFileRequest, UploadFileResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedSkeeperServiceServer) GetFile(*GetFileRequest, grpc.ServerStreamingServer[GetFileResponse]) error {
	return status.Error(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedSkeeperServiceServer) SyncEntries(grpc.BidiStreamingServer[SyncEntriesRequest, SyncEntriesResponse]) error {
	return status.Error(codes.Unimplemented, "method SyncEntries not implemented")
}
func (UnimplementedSkeeperServiceServer) mustEmbedUnimplementedSkeeperServiceServer() {}
func (UnimplementedSkeeperServiceServer) testEmbeddedByValue()                        {}

// UnsafeSkeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkeeperServiceServer will
// result in compilation errors.
type UnsafeSkeeperServiceServer interface {
	mustEmbedUnimplementedSkeeperServiceServer()
}

func RegisterSkeeperServiceServer(s grpc.ServiceRegistrar, srv SkeeperServiceServer) {
	// If the following call panics, it indicates UnimplementedSkeeperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkeeperService_ServiceDesc, srv)
}

func _SkeeperService_ListEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEntriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SkeeperServiceServer).ListEntries(m, &grpc.GenericServerStream[ListEntriesRequest, ListEntriesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_ListEntriesServer = grpc.ServerStreamingServer[ListEntriesResponse]

func _SkeeperService_GetEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEntriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SkeeperServiceServer).GetEntries(m, &grpc.GenericServerStream[GetEntriesRequest, GetEntriesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_GetEntriesServer = grpc.ServerStreamingServer[GetEntriesResponse]

func _SkeeperService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SkeeperServiceServer).UploadFile(&grpc.GenericServerStream[UploadFileRequest, UploadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_UploadFileServer = grpc.ClientStreamingServer[UploadFileRequest, UploadFileResponse]

func _SkeeperService_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SkeeperServiceServer).GetFile(m, &grpc.GenericServerStream[GetFileRequest, GetFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_GetFileServer = grpc.ServerStreamingServer[GetFileResponse]

func _SkeeperService_SyncEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SkeeperServiceServer).SyncEntries(&grpc.GenericServerStream[SyncEntriesRequest, SyncEntriesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkeeperService_SyncEntriesServer = grpc.BidiStreamingServer[SyncEntriesRequest, SyncEntriesResponse]

// SkeeperService_ServiceDesc is the grpc.ServiceDesc for SkeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skeeper.SkeeperService",
	HandlerType: (*SkeeperServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEntries",
			Handler:       _SkeeperService_ListEntries_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetEntries",
			Handler:       _SkeeperService_GetEntries_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _SkeeperService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetFile",
			Handler:       _SkeeperService_GetFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncEntries",
			Handler:       _SkeeperService_SyncEntries_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/skeeper.proto",
}
